import { promises as fs } from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const OUT = path.resolve(ROOT, process.argv.find(a=>a.startsWith('--dir='))?.split('=')[1] || 'dist');
const SITE = 'https://www.eslam-elshikh.com';
const MODIFIED = '2026-07-30';
const GA_ID = 'G-MDJ2HGF9E1';
const LOGO = '/assets/brand/eslam-elshikh-logo-2026.svg';
const PROFILE = '/assets/brand/eslam-elshikh-profile-2026.svg';

const ga = `<!-- Google tag (gtag.js) -->\n<script async src="https://www.googletagmanager.com/gtag/js?id=${GA_ID}"></script>\n<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${GA_ID}',{anonymize_ip:true});</script>`;

const extraCss = `
<style id="final-seo-ui">
.stat-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1rem;margin:2rem 0}.stat-card{padding:1.5rem;border:1px solid color-mix(in srgb,var(--accent,#52d6b7) 28%,transparent);border-radius:22px;background:color-mix(in srgb,var(--surface,#092032) 94%,transparent);text-align:center;box-shadow:0 16px 50px rgba(0,0,0,.12)}.stat-number{display:block;font-size:clamp(2rem,6vw,4rem);font-weight:800;color:var(--accent,#52d6b7);line-height:1}.stat-label{display:block;margin-top:.7rem;line-height:1.8}.profile-identity-img{width:clamp(110px,20vw,190px);aspect-ratio:1;border-radius:50%;object-fit:cover}.service-area-note{margin:2rem 0;padding:1.4rem;border-radius:20px;border:1px solid rgba(82,214,183,.25);background:rgba(82,214,183,.07)}.article-prose{max-width:900px;margin:auto}.article-prose h2{margin-top:2.2rem}.article-prose p,.article-prose li{line-height:2}.faq-list details{margin:.75rem 0;padding:1rem 1.1rem;border:1px solid rgba(128,160,180,.22);border-radius:16px}.faq-list summary{cursor:pointer;font-weight:700}.blog-card-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.blog-card{padding:1.25rem;border:1px solid rgba(128,160,180,.2);border-radius:18px}.blog-card a{font-weight:800}.site-logo img[src*="logo"],img.brand-logo{content:url('${LOGO}')}.about-card img,.profile-card img,.hero-card img[alt*="Eslam"],.hero-card img[alt*="إسلام"]{content:url('${PROFILE}');border-radius:50%;object-fit:cover}
@media(max-width:800px){.stat-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.blog-card-grid{grid-template-columns:1fr}}
@media(prefers-reduced-motion:reduce){[data-counter]{transition:none!important;animation:none!important}}
</style>`;

const counterJs = `<script id="counter-script">(()=>{const els=[...document.querySelectorAll('[data-counter]')];if(!els.length)return;const run=e=>{const target=Number(e.dataset.counter);const suffix=e.dataset.suffix||'';if(matchMedia('(prefers-reduced-motion: reduce)').matches){e.textContent=target.toLocaleString('en-US')+suffix;return}const start=performance.now(),duration=1400;const tick=t=>{const p=Math.min(1,(t-start)/duration);const v=Math.floor(target*(1-Math.pow(1-p,3)));e.textContent=v.toLocaleString('en-US')+suffix;if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)};const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting&&!x.target.dataset.done){x.target.dataset.done='1';run(x.target);io.unobserve(x.target)}}),{threshold:.35});els.forEach(e=>io.observe(e))})();</script>`;

const stats = `<section class="section" id="impact-numbers" aria-labelledby="impact-title"><div class="container"><p class="eyebrow">أرقام من الخبرة العملية</p><h2 id="impact-title">نتائج ومساهمات رقمية قابلة للقياس</h2><div class="stat-grid"><article class="stat-card"><strong class="stat-number" data-counter="1411" data-suffix="+">0</strong><span class="stat-label">مساهمة في توثيق وإدارة ملفات Google التجارية</span></article><article class="stat-card"><strong class="stat-number" data-counter="105" data-suffix="+">0</strong><span class="stat-label">موقع وتطبيق ومتجر إلكتروني تم تصميمها وتطويرها</span></article><article class="stat-card"><strong class="stat-number" data-counter="653" data-suffix="+">0</strong><span class="stat-label">مساعد بالذكاء الاصطناعي ومشروع سحابي</span></article><article class="stat-card"><strong class="stat-number" data-counter="360" data-suffix="°">0</strong><span class="stat-label">رؤية تجمع الأمن والتطوير والظهور الرقمي</span></article></div></div></section>`;

const serviceArea = `<section class="service-area-note" aria-label="نطاق الخدمة"><strong>نطاق الخدمة: جميع أحياء مدينة الرياض</strong><p>تُقدَّم الاستشارات والخدمات عن بُعد، مع إمكانية زيارة مواقع العملاء داخل الرياض بموعد مسبق. النشاط يعمل كنشاط ضمن منطقة خدمة، ولا يستقبل العملاء في عنوان سكني معلن.</p></section>`;

const articles = [
['web-design-riyadh','تصميم مواقع احترافية في الرياض: دليل بناء موقع يحول الزيارات إلى عملاء','تصميم مواقع ويب','كيف تختار بنية موقع سريعة ومتجاوبة وتخدم السيو والتحويل والثقة؟','تصميم الموقع الناجح لا يبدأ بالألوان، بل يبدأ بفهم الخدمة والعميل ومسار القرار. الموقع الذي يبدو جميلًا ولا يشرح العرض ولا يقود الزائر إلى خطوة واضحة يستهلك الميزانية دون أثر تجاري. في سوق الرياض التنافسي، تحتاج الشركات إلى موقع سريع على الجوال، واضح في اللغة، موثوق تقنيًا، ومبني حول صفحات خدمات حقيقية بدل صفحة عامة مبهمة.','يشمل العمل المهني تحليل نية البحث، وبناء هيكل معلومات، وتصميم واجهة متجاوبة، وكتابة محتوى يجيب عن الأسئلة، ثم تنفيذ تقني يحافظ على الأداء وإمكانية الفهرسة. كما يجب تحديد مؤشرات قياس مثل النقر على الاتصال، وإرسال النموذج، وفتح واتساب، والوصول إلى صفحات الخدمات المهمة.','ابدأ بتحديد الهدف التجاري، ثم اجمع الخدمات في مجموعات منطقية، وأنشئ لكل خدمة صفحة مستقلة بعنوان واضح ووصف ميتا دقيق. بعد ذلك اربط الصفحات بمقالات مساندة، واستخدم صورًا محسنة، وخطوطًا محلية، وتحميلًا كسولًا للعناصر غير الحرجة، واختبر تجربة الاستخدام على أجهزة فعلية.'],
['secure-web-development','تطوير مواقع آمنة: كيف تجمع بين الأداء والحماية وتجربة المستخدم','الأمن السيبراني وتطوير الويب','الأمان ليس إضافة بعد الإطلاق؛ بل قرار معماري يبدأ من أول سطر.','تطوير موقع آمن يعني تقليل سطح الهجوم، وضبط الصلاحيات، وحماية الجلسات والنماذج، وتحديث المكونات، ومراقبة الأخطاء. لا يكفي تركيب شهادة SSL أو إضافة أداة حماية جاهزة، لأن المخاطر قد تأتي من منطق التطبيق، أو إعدادات التخزين، أو مفاتيح الخدمات، أو رفع الملفات، أو اعتماد مكتبات قديمة.','المنهج الصحيح يبدأ بنموذج تهديد بسيط يحدد الأصول الحساسة ومسارات الاستخدام المحتملة. ثم تُطبق مبادئ أقل صلاحية، والتحقق من المدخلات، والتشفير أثناء النقل، وسياسات المتصفح، والنسخ الاحتياطي، وخطة الاستجابة للحوادث.','تتضمن المراجعة العملية فحص رؤوس الأمان، وسياسة المحتوى CSP، وإدارة الأسرار، وإعدادات CORS، ومنع النقر الخادع، ومراقبة الاعتمادات. ويجب ألا تضر إجراءات الحماية بإمكانية الاستخدام أو الفهرسة، بل تُنفذ بتوازن واختبارات واضحة.'],
['google-business-profile-riyadh','تحسين ملف Google التجاري في الرياض لنشاط ضمن منطقة خدمة','ملف Google التجاري','كيف تنشئ ملفًا متوافقًا عندما تزور العملاء ولا تستقبلهم في مقر معلن؟','النشاط الذي ينتقل إلى مواقع العملاء داخل الرياض يمكنه استخدام نموذج منطقة الخدمة مع إخفاء عنوان السكن عن الجمهور. الهدف هو تقديم بيانات دقيقة ومتسقة: اسم حقيقي مستخدم في الواقع، فئة رئيسية تصف النشاط، هاتف وموقع موحدان، وخدمات واضحة دون حشو كلمات مفتاحية.','في حالة الخدمات التقنية، يمكن أن تكون الفئة الرئيسية مصمم مواقع ويب عندما يكون تصميم وتطوير المواقع هو النشاط الأبرز، مع فئات إضافية دقيقة مثل استشاري كمبيوتر وخدمة التسويق عبر الإنترنت ودعم الكمبيوتر والخدمات عند تقديمها فعليًا.','قوة الملف لا تأتي من كثرة التعديلات، بل من الاتساق، والمراجعات الحقيقية، والصور الأصلية، ونشر التحديثات المفيدة، وربط الموقع بصفحات خدمات محلية قوية. كما يجب الاستعداد للتحقق بأدلة تشغيل حقيقية دون إظهار بيانات حساسة أو ادعاء ارتباط رسمي بمنصة Google.'],
['local-seo-riyadh','السيو المحلي في الرياض: خطة عملية للظهور أمام العملاء القريبين','السيو المحلي','الظهور المحلي نتيجة منظومة مترابطة بين الموقع والملف التجاري والسمعة.','السيو المحلي ليس تكرار اسم المدينة في كل سطر. يبدأ بفهم المناطق التي تخدمها فعليًا، وتحديد الخدمات الأكثر طلبًا، وكتابة صفحات تجيب عن نية الباحث، ثم توحيد بيانات النشاط وربط الموقع بملف Google التجاري.','صفحة الخدمة المحلية الجيدة تشرح المشكلة، ومن تناسبه الخدمة، وخطوات التنفيذ، وما الذي يحصل عليه العميل، والأسئلة الشائعة. كما تقدم دلائل ثقة حقيقية مثل نماذج أعمال وسياسات واضحة وطرق تواصل مباشرة.','تقنيًا يجب ضبط العنوان والوصف والروابط الأساسية والبيانات المنظمة وخريطة الموقع والربط الداخلي. ولا ينبغي إنشاء عشرات صفحات الأحياء المتشابهة؛ الأفضل إنشاء محتوى أصلي يخدم مناطق الرياض بصدق ويضيف قيمة حقيقية.'],
['technical-seo-audit','التدقيق التقني للسيو: قائمة فحص لتحسين الفهرسة والأداء','تحسين محركات البحث','قبل زيادة المحتوى، تأكد أن محركات البحث تستطيع الوصول والفهم والاختيار.','التدقيق التقني يفحص قابلية الزحف، والفهرسة، والروابط الأساسية، وخرائط الموقع، والصفحات المكررة، والبيانات المنظمة، وسرعة العرض، واستقرار التخطيط، وتجربة الجوال. أي خلل في هذه الطبقات قد يمنع المحتوى القوي من تحقيق فرصته.','يبدأ الفحص بتحديد النسخة الأساسية للنطاق وتوحيد www وHTTPS والشرطات النهائية. ثم تُراجع حالات الاستجابة والتحويلات والصفحات اليتيمة والروابط المكسورة والعناوين المكررة.','بعد الإصلاح، يجب قياس الأثر في Search Console وAnalytics بدل الاعتماد على الانطباع. الأولوية للمشكلات التي تمنع الفهرسة أو تربك النسخة الأساسية، ثم الأداء وتجربة المستخدم، ثم التحسينات الدلالية الدقيقة.'],
['ai-agents-business','وكلاء الذكاء الاصطناعي للأعمال: من الفكرة إلى مساعد قابل للقياس','الذكاء الاصطناعي','المساعد الناجح ليس نافذة محادثة فقط؛ بل سير عمل موثوق بحدود واضحة.','يبدأ بناء وكيل ذكاء اصطناعي بتحديد مهمة ضيقة يمكن قياسها، مثل فرز الطلبات، أو الإجابة من قاعدة معرفة، أو إعداد مسودة، أو استدعاء أدوات محددة. توسيع النطاق مبكرًا يزيد الأخطاء والتكلفة وصعوبة المراجعة.','يجب فصل المعرفة عن التعليمات، وتحديد مصادر الحقيقة، وتسجيل الإجراءات، ووضع موافقات بشرية عند العمليات الحساسة. كما يلزم تصميم حالات الفشل: ماذا يحدث عند غياب البيانات أو تضاربها أو طلب إجراء غير مسموح؟','القياس يشمل دقة الإجابة، ونسبة الإكمال، وزمن الاستجابة، وتكلفة التشغيل، وعدد الحالات التي احتاجت تدخلًا بشريًا. بهذه الطريقة يتحول الذكاء الاصطناعي من عرض مبهر إلى أداة إنتاجية يمكن تحسينها.'],
['cloud-solutions-saudi','الحلول السحابية للشركات: اختيار بنية مرنة وآمنة دون تعقيد','الحوسبة السحابية','القرار السحابي الجيد يوازن بين المرونة والتكلفة والأمان وقابلية التشغيل.','الانتقال إلى السحابة لا يعني نقل كل شيء كما هو. يجب تصنيف الأنظمة والبيانات، وفهم متطلبات التوفر والنسخ الاحتياطي، واختيار خدمات مُدارة عندما تقلل العبء التشغيلي بوضوح.','تشمل الأساسيات إدارة الهوية والصلاحيات، وفصل البيئات، وتشفير البيانات، ومراقبة السجلات، وتحديد ميزانيات وتنبيهات للتكلفة. كما يجب توثيق الاعتمادات وخطة الاستعادة بدل الاعتماد على معرفة شخص واحد.','أفضل بنية ليست الأكثر تعقيدًا، بل الأبسط التي تحقق المتطلبات الحالية وتسمح بالنمو. لذلك تُبنى القرارات على أحمال حقيقية ومؤشرات استخدام، مع مراجعات دورية للتكلفة والمخاطر والأداء.'],
['ecommerce-design','تصميم متجر إلكتروني احترافي: تجربة شراء سريعة وآمنة','المتاجر الإلكترونية','كل خطوة غير واضحة في رحلة الشراء قد تتحول إلى سلة مهجورة.','المتجر الناجح يجمع بين تصنيف مفهوم، وبحث فعال، وصفحات منتجات مقنعة، وصور خفيفة، وسياسات واضحة، ودفع آمن. يجب أن ينجح المسار كاملًا على الجوال لأن نسبة كبيرة من العملاء تبدأ وتنهي القرار من الهاتف.','صفحة المنتج تحتاج عنوانًا دقيقًا، ووصفًا يشرح الفائدة، ومواصفات منظمة، ومعلومات شحن وإرجاع، وأسئلة متوقعة، وبيانات منظمة للمنتج عند انطباقها. كما ينبغي منع الفلاتر والمعلمات من إنشاء آلاف الصفحات المكررة.','التحسين المستمر يعتمد على قياس مشاهدة المنتج والإضافة للسلة وبدء الدفع والشراء، ثم اختبار نقاط التسرب. السرعة والثقة والوضوح غالبًا أكثر تأثيرًا من الزخارف البصرية الثقيلة.'],
['conversion-landing-pages','صفحات الهبوط عالية التحويل: كتابة وتصميم يقودان إلى قرار واضح','تصميم صفحات الهبوط','صفحة الهبوط لها هدف واحد ومسار واحد وقياس واحد رئيسي.','تبدأ الصفحة بعنوان يطابق الإعلان أو نية البحث، ثم توضح المشكلة والنتيجة المقترحة والدليل والخطوات والاعتراضات الشائعة. كثرة الروابط والرسائل المتنافسة تشتت الزائر وتضعف التحويل.','التصميم الجيد يستخدم تسلسلًا بصريًا واضحًا، وأزرارًا مفهومة، ونموذجًا قصيرًا، ومساحات مريحة، ومحتوى يمكن مسحه بصريًا. كما يجب أن تكون الصفحة سريعة وأن يعمل الاتصال وواتساب والنماذج دون احتكاك.','لا يُحكم على الصفحة من جمالها فقط، بل من بياناتها. يجب تعريف الأحداث في Analytics، ومقارنة مصادر الزيارات، واختبار العناوين والعروض والنماذج تدريجيًا دون تغيير كل شيء دفعة واحدة.'],
['schema-structured-data','البيانات المنظمة Schema: كيف تساعد محركات البحث على فهم موقعك','السيو التقني والبيانات المنظمة','البيانات المنظمة توضح المعنى، لكنها لا تعوض محتوى ضعيفًا أو معلومات غير صحيحة.','تُستخدم Schema لوصف الشخص أو المؤسسة والخدمات والمقالات ومسار التنقل والأسئلة الشائعة عند ظهورها فعلًا في الصفحة. يجب أن تتطابق البيانات مع المحتوى المرئي، وأن تستخدم روابط ثابتة ومعرّفات @id متسقة.','من الأخطاء الشائعة تكرار كيانات متعارضة، واستخدام عنوان غير معلن لنشاط منطقة خدمة، وإضافة تقييمات ذاتية، وترك mainEntity في ProfilePage، أو وضع تاريخ بصيغة غير صحيحة.','بعد الإضافة تُفحص الصياغة والحقول المطلوبة وأهلية النتائج الغنية، ثم تُراقب Search Console. الظهور كمقتطف منسق ليس مضمونًا، لكنه يصبح أكثر احتمالًا عندما تكون البيانات صحيحة والمحتوى مفيدًا والصفحة موثوقة.']
];

const faqs = [
['هل هذه الخدمة مناسبة للشركات الصغيرة؟','نعم، بشرط تحديد نطاق واضح وأولوية قابلة للقياس بدل تنفيذ قائمة طويلة من الخصائص غير الضرورية.'],
['كم يستغرق التنفيذ؟','تختلف المدة حسب النطاق والمحتوى والتكاملات، وتُحدد بعد مراجعة المتطلبات والمخرجات ومعيار القبول.'],
['هل يمكن تنفيذ الخدمة عن بُعد؟','نعم، وتتوفر زيارات لمواقع العملاء داخل مدينة الرياض بموعد مسبق عندما تتطلب المهمة ذلك.'],
['هل النتائج مضمونة؟','يمكن ضمان جودة التنفيذ والمخرجات المتفق عليها، أما ترتيب البحث أو قرارات المنصات الخارجية فلا يمكن ضمانها لأنها تعتمد على عوامل متعددة.'],
['كيف يبدأ العمل؟','يبدأ بتشخيص الاحتياج، ثم تحديد النطاق والأولويات والمخرجات والقياس، وبعد الموافقة تبدأ مرحلة التنفيذ والمراجعة.']
];

const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const articlePage = ([slug,title,topic,lead,p1,p2,p3]) => {
 const url=`${SITE}/blog/${slug}/`;
 const faqHtml=faqs.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('');
 const schema={"@context":"https://schema.org","@graph":[{"@type":"BlogPosting","@id":`${url}#article`,headline:title,description:lead,datePublished:MODIFIED,dateModified:MODIFIED,inLanguage:"ar",mainEntityOfPage:{"@id":url},author:{"@id":`${SITE}/#person`},publisher:{"@id":`${SITE}/#person`},image:`${SITE}${PROFILE}`},{"@type":"WebPage","@id":url,url,name:title,inLanguage:"ar",dateModified:MODIFIED,mainEntity:{"@id":`${url}#article`},isPartOf:{"@id":`${SITE}/#website`}},{"@type":"FAQPage","@id":`${url}#faq`,mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"الرئيسية",item:`${SITE}/`},{"@type":"ListItem",position:2,name:"المدونة",item:`${SITE}/blog/`},{"@type":"ListItem",position:3,name:title,item:url}]}]};
 return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | المهندس إسلام الشيخ</title><meta name="description" content="${esc(lead)}"><link rel="canonical" href="${url}"><link rel="stylesheet" href="/assets/css/main.css"><link rel="stylesheet" href="/assets/css/improvements.css">${ga}${extraCss}<script type="application/ld+json">${JSON.stringify(schema)}</script></head><body><header class="site-header"><div class="container"><a class="site-logo" href="/"><img src="${LOGO}" alt="المهندس إسلام الشيخ" width="72" height="72"></a><nav><a href="/">الرئيسية</a> <a href="/services/">الخدمات</a> <a href="/blog/">المدونة</a> <a href="/contact/">تواصل</a></nav></div></header><main><article class="section article-prose"><p class="eyebrow">${topic}</p><h1>${title}</h1><p class="lead">${lead}</p><img class="profile-identity-img" src="${PROFILE}" alt="المهندس إسلام الشيخ" width="180" height="180"><h2>لماذا يحتاج المشروع إلى منهج متكامل؟</h2><p>${p1}</p><h2>ما الذي يشمله التنفيذ الاحترافي؟</h2><p>${p2}</p><h2>خطوات عملية لتحسين النتيجة</h2><p>${p3}</p><p>تنجح المشاريع الرقمية عندما تكون القرارات موثقة ويمكن مراجعتها: من يملك المحتوى؟ ما البيانات المطلوبة؟ ما مؤشرات الأداء؟ وما حدود المسؤولية بين العميل والمنصات الخارجية؟ وضوح هذه الأسئلة يقلل إعادة العمل ويجعل التطوير والصيانة أسرع.</p><h2>أخطاء شائعة ينبغي تجنبها</h2><ul><li>البدء في التصميم أو البرمجة قبل تثبيت الهدف ومسار المستخدم.</li><li>تكرار المحتوى أو الكلمات المفتاحية دون قيمة حقيقية للقارئ.</li><li>إهمال تجربة الجوال والأداء وإمكانية الوصول.</li><li>استخدام ادعاءات أو أرقام أو تقييمات غير قابلة للتحقق.</li><li>عدم إعداد القياس والنسخ الاحتياطي وخطة الصيانة.</li></ul><h2>كيف تقيس نجاح المشروع؟</h2><p>حدد مؤشرات مرتبطة بالهدف: جودة الطلبات، ونسبة التحويل، وزمن تنفيذ المهمة، والأخطاء، والظهور العضوي، وسرعة الصفحات. ثم راقب الاتجاه على مدى مناسب بدل الحكم من يوم واحد. البيانات الجيدة تساعد على ترتيب التحسينات حسب أثرها لا حسب الانطباع.</p><section class="faq-list"><h2>الأسئلة الشائعة</h2>${faqHtml}</section>${serviceArea}<p><a class="button" href="/contact/">اطلب استشارة للمشروع</a></p></article></main>${counterJs}</body></html>`;
};

async function walk(dir){const out=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())out.push(...await walk(p));else out.push(p)}return out}
function patchJsonLd(html){return html.replace(/<script([^>]*type=["']application\/ld\+json["'][^>]*)>([\s\S]*?)<\/script>/gi,(m,a,b)=>{try{const data=JSON.parse(b);const fix=o=>{if(!o||typeof o!=='object')return;if(Array.isArray(o)){o.forEach(fix);return}for(const [k,v] of Object.entries(o)){if(typeof v==='string')o[k]=v.replaceAll('https://eslam-elshikh.com','https://www.eslam-elshikh.com');else fix(v)}if(o['@type']==='ProfilePage'){o.dateModified=MODIFIED;o.mainEntity=o.mainEntity||{'@id':`${SITE}/#person`};o.url=o.url||`${SITE}/about/`}if(['Person','ProfessionalService','LocalBusiness'].includes(o['@type'])){o.areaServed={"@type":"City",name:"الرياض"};delete o.address;if(o.logo)o.logo=`${SITE}${LOGO}`;if(o.image)o.image=`${SITE}${PROFILE}`}if(o.dateModified)o.dateModified=MODIFIED};fix(data);return `<script${a}>${JSON.stringify(data)}</script>`}catch{return m}})}

async function patchHtml(file){let h=await fs.readFile(file,'utf8');h=h.replaceAll('https://eslam-elshikh.com','https://www.eslam-elshikh.com');h=patchJsonLd(h);if(!h.includes(GA_ID))h=h.replace('</head>',`${ga}\n${extraCss}\n</head>`);if(!h.includes('counter-script'))h=h.replace('</body>',`${counterJs}\n</body>`);h=h.replace(/src=["'][^"']*eslam-elshikh-logo[^"']*["']/gi,`src="${LOGO}"`);h=h.replace(/src=["']https:\/\/avatars\.githubusercontent\.com\/[^"']+["']/gi,`src="${PROFILE}"`);if(/<body[^>]*>[\s\S]*?<main/i.test(h)&&/\/about\/index\.html$/.test(file.replaceAll('\\','/'))){h=h.replace(/(<img[^>]+)(src=["'][^"']+["'])([^>]*alt=["'][^"']*(?:Eslam|إسلام)[^"']*["'][^>]*>)/i,`$1src="${PROFILE}"$3`)}if(/\/index\.html$/.test(file.replaceAll('\\','/'))&&!file.replaceAll('\\','/').includes('/blog/')&&path.dirname(file)===OUT&&!h.includes('impact-numbers'))h=h.replace('</main>',`${stats}${serviceArea}</main>`);if(file.includes(`${path.sep}services${path.sep}`)&&file.endsWith('index.html')&&!h.includes('faq-list')){const title=(h.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||'الخدمة').replace(/<[^>]+>/g,'');const faq=`<section class="section faq-list"><div class="container"><h2>أسئلة شائعة عن ${title}</h2>${faqs.slice(0,4).map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></section>`;h=h.replace('</main>',`${faq}</main>`)}await fs.writeFile(file,h)}

await fs.mkdir(path.join(OUT,'assets','brand'),{recursive:true});
for(const name of ['eslam-elshikh-logo-2026.svg','eslam-elshikh-profile-2026.svg']){const src=path.join(ROOT,'assets','brand',name);try{await fs.copyFile(src,path.join(OUT,'assets','brand',name))}catch{}}
for(const a of articles){const dir=path.join(OUT,'blog',a[0]);await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'index.html'),articlePage(a))}
for(const f of (await walk(OUT)).filter(x=>x.endsWith('.html')))await patchHtml(f);
const blog=path.join(OUT,'blog','index.html');try{let h=await fs.readFile(blog,'utf8');const cards=`<section class="section"><div class="container"><h2>أدلة ومقالات متخصصة</h2><div class="blog-card-grid">${articles.map(([s,t,topic,lead])=>`<article class="blog-card"><p class="eyebrow">${topic}</p><h3><a href="/blog/${s}/">${t}</a></h3><p>${lead}</p></article>`).join('')}</div></div></section>`;if(!h.includes('/blog/web-design-riyadh/'))h=h.replace('</main>',`${cards}</main>`);await fs.writeFile(blog,h)}catch{}
const sitemap=path.join(OUT,'sitemap.xml');try{let x=await fs.readFile(sitemap,'utf8');x=x.replaceAll('https://eslam-elshikh.com','https://www.eslam-elshikh.com');const rows=articles.map(([s])=>`<url><loc>${SITE}/blog/${s}/</loc><lastmod>${MODIFIED}</lastmod></url>`).join('');if(!x.includes('/blog/web-design-riyadh/'))x=x.replace('</urlset>',`${rows}</urlset>`);await fs.writeFile(sitemap,x)}catch{}
console.log(`Final SEO, identity, analytics and ${articles.length} articles applied to ${OUT}`);
