export function renderAbout({ site, mapsCount, projectCount, projects, profilePhoto, innerHero, icon, eyebrow, button, esc, projectImage, finalCta }) {
  const signatureWords = ["UNDERSTAND", "SECURE", "BUILD", "AUTOMATE", "MEASURE", "ESLAM ELSHIKH"];
  const signatureTrack = [...signatureWords, ...signatureWords]
    .map((word) => `<span>${word}<i></i></span>`)
    .join("");

  const focusAreas = [
    {
      key: "secure",
      number: "01",
      label: "الأمن",
      english: "SECURE",
      icon: "shield",
      title: "أجعل الأمان أصلًا في القرار، لا بندًا مؤجلًا.",
      text: "أتعامل مع الأمن السيبراني بوصفه جزءًا من هندسة المشروع منذ بدايته: أفهم البيانات والصلاحيات ومسارات الدخول والأثر التجاري، ثم أحوّل المخاطر إلى أولويات واضحة يستطيع الفريق تنفيذها والتحقق منها.",
      points: ["تقييم المخاطر والثغرات", "مراجعة الصلاحيات والبنية", "معالجة قابلة للاختبار"],
      href: "/services/cybersecurity/",
      cta: "استكشف مسار الأمن السيبراني"
    },
    {
      key: "build",
      number: "02",
      label: "البرمجيات",
      english: "BUILD",
      icon: "code",
      title: "أبني مواقع سريعة وآمنة تقود الزائر إلى القرار.",
      text: "في تطوير المواقع والبرمجيات، أحوّل الهدف التجاري إلى بنية محتوى وتجربة عربية وكود سريع ومتجاوب. كل تفصيلة تخدم مسارًا مفهومًا من أول انطباع إلى الإجراء المطلوب، مع قابلية حقيقية للصيانة والتوسع.",
      points: ["تجربة عربية Mobile First", "أداء وسيو تقني من البداية", "تحويل وقياس بلا غموض"],
      href: "/services/web-development/",
      cta: "استكشف تطوير المواقع"
    },
    {
      key: "automate",
      number: "03",
      label: "الذكاء الاصطناعي",
      english: "AUTOMATE",
      icon: "spark",
      title: "أحوّل الذكاء الاصطناعي من عرضٍ مبهر إلى عملٍ منضبط.",
      text: "أبدأ من المهمة التي تستنزف وقت الفريق، ثم أحدد المعرفة والأدوات والصلاحيات وموضع التدخل البشري. النتيجة وكيل ذكاء اصطناعي يؤدي وظيفة محددة، ويمكن تقييمه ومراقبته وتحسينه.",
      points: ["وكلاء AI لحالات فعلية", "RAG وربط المعرفة والأدوات", "تقييم ورقابة بشرية"],
      href: "/services/ai-agents/",
      cta: "استكشف وكلاء الذكاء الاصطناعي"
    },
    {
      key: "grow",
      number: "04",
      label: "Google والظهور",
      english: "GROW",
      icon: "google",
      title: "أجعل الظهور المحلي منظومة ثقة، لا مصادفة ترتيب.",
      text: "أربط ملف Google التجاري بالموقع والمحتوى واتساق البيانات والسياسات، وأعالج التحقق والملكية والقيود والتصنيف بمنهج واضح يخدم خرائط Google والسيو المحلي، من دون وعد بقرار منصة أو ترتيب مضمون.",
      points: ["إثبات الملكية والتوثيق", "تشخيص القيود والمشكلات", "خرائط Google والسيو المحلي"],
      href: "/google-expert/",
      cta: "استكشف خبرة خرائط Google"
    }
  ];

  const focusTabs = focusAreas.map((area, index) => `<button type="button" id="about-focus-tab-${area.key}" role="tab" aria-controls="about-focus-panel-${area.key}" aria-selected="${index === 0 ? "true" : "false"}" tabindex="${index === 0 ? "0" : "-1"}" data-about-focus-tab="${area.key}"><span>${area.number}</span><span><strong>${area.label}</strong><small>${area.english}</small></span></button>`).join("");
  const focusPanels = focusAreas.map((area, index) => `<div class="about-focus-panel${index === 0 ? " is-active" : ""}" id="about-focus-panel-${area.key}" role="tabpanel" aria-labelledby="about-focus-tab-${area.key}" tabindex="0" data-about-focus-panel="${area.key}"><div class="about-focus-art" aria-hidden="true"><span>${area.number}</span><div>${icon(area.icon)}</div><small>${area.english}</small></div><div class="about-focus-copy"><span>زاوية الخبرة · ${area.label}</span><h3>${area.title}</h3><p>${area.text}</p><ul>${area.points.map((point) => `<li>${icon("check")}<span>${point}</span></li>`).join("")}</ul><a class="text-link" href="${area.href}">${area.cta} ${icon("arrow")}</a></div></div>`).join("");
  const caseStudyProjects = projects.filter((project) => project.caseStudy && project.slug).slice(0, 3);
  const caseStudyCards = caseStudyProjects.map((project, index) => `<article class="about-case-card reveal"><a class="about-case-media" href="/projects/${project.slug}/" aria-label="قراءة دراسة حالة ${esc(project.title)}"><span dir="ltr">CASE / ${String(index + 1).padStart(2, "0")}</span>${projectImage(project)}</a><div class="about-case-copy"><p class="about-case-category">${esc(project.category)}</p><h4><a href="/projects/${project.slug}/">${esc(project.title)}</a></h4><p>${esc(project.description)}</p><div class="about-case-tags" aria-label="مجالات المشروع">${project.tags.slice(0, 2).map((tag) => `<span>${esc(tag)}</span>`).join("")}</div><div class="about-case-links"><a class="text-link" href="/projects/${project.slug}/" aria-label="قراءة دراسة حالة ${esc(project.title)}">دراسة الحالة ${icon("arrow")}</a><a class="about-case-live" href="${project.liveUrl}" target="_blank" rel="noopener" aria-label="فتح موقع ${esc(project.title)} المنشور">الموقع الحي ${icon("external")}</a></div></div></article>`).join("");
  const heroUtility = `<div class="about-hero-actions">${button("/contact/", "ناقش مشروعك")}${button("/projects/", "شاهد دراسات الحالة", "button-ghost")}</div><ul class="about-quick-facts" aria-label="معلومات سريعة عن إسلام الشيخ"><li>${icon("pin")}<span><small>الموقع</small><strong>الرياض، السعودية</strong></span></li><li>${icon("nodes")}<span><small>نطاق التعاون</small><strong>السعودية وعن بُعد</strong></span></li><li>${icon("target")}<span><small>نقطة البداية</small><strong>تشخيص ونطاق واضح</strong></span></li></ul>`;

  return `${innerHero({ eyebrowText: "عن المهندس إسلام الشيخ · هندسة رقمية متكاملة", title: `أنا المهندس إسلام الشيخ. <span class="about-h1-line">أبني الأمان والبرمجيات والظهور الرقمي كمنظومةٍ واحدة.</span>`, lead: "مهندس أمن سيبراني ومطور مواقع وبرمجيات في الرياض، وخبير منتجات Google. أساعد الشركات وأصحاب الأعمال على بناء حلول رقمية آمنة وسريعة وواضحة، من التشخيص وتصميم التجربة إلى الإطلاق والقياس.", afterLead: heroUtility, path: "/about/", crumbs: [{ name: "عن إسلام", path: "/about/" }], className: "about-hero about-hero-v2", aside: `<div class="about-identity-card about-identity-card-v2"><span class="about-system-status"><i></i>PROFILE / ACTIVE</span><div class="about-orbit-map"><span class="about-orbit-ring about-orbit-ring-a" aria-hidden="true"></span><span class="about-orbit-ring about-orbit-ring-b" aria-hidden="true"></span><img class="about-portrait" src="${profilePhoto}" width="280" height="280" alt="صورة المهندس إسلام الشيخ" decoding="async"><span class="about-orbit-node about-orbit-secure" aria-hidden="true">${icon("shield")}<b>SECURE</b></span><span class="about-orbit-node about-orbit-build" aria-hidden="true">${icon("code")}<b>BUILD</b></span><span class="about-orbit-node about-orbit-ai" aria-hidden="true">${icon("spark")}<b>AI</b></span><span class="about-orbit-node about-orbit-grow" aria-hidden="true">${icon("google")}<b>GROW</b></span></div><div class="about-identity-copy"><span class="about-identity-label">DIGITAL ENGINEER · RIYADH</span><strong>${site.nameAr}</strong><p>Cybersecurity · Software · AI · Google</p><div class="about-identity-links"><a href="${site.social.googleDeveloper}" target="_blank" rel="noopener">Google للمطورين ${icon("external")}</a><a href="${site.social.github}" target="_blank" rel="noopener">GitHub ${icon("external")}</a><a href="${site.social.wikidata}" target="_blank" rel="noopener">Wikidata ${icon("external")}</a></div><small>خبير مستقل؛ لا أمثل Google أو أي منصة خارجية.</small></div></div>` })}
<div class="about-signature-strip" role="note" aria-label="منهج إسلام الشيخ: فهم، حماية، بناء، أتمتة، وقياس"><div class="about-signature-track" aria-hidden="true">${signatureTrack}</div></div>
<section class="about-name-registry" aria-labelledby="about-name-registry-title"><div class="container"><div class="about-name-registry-head reveal"><span>IDENTITY / ONE ENTITY</span><h2 id="about-name-registry-title">اسمٌ واحد، وصيغ كتابةٍ واضحة.</h2><p>المرجع الرسمي هو المهندس إسلام الشيخ، وتُستخدم الصيغ التالية لتوحيد الهوية العربية والإنجليزية عبر الموقع والملفات المهنية والأعمال المنشورة.</p></div><dl class="about-name-grid reveal"><div><dt>الاسم المهني بالعربية</dt><dd>المهندس إسلام الشيخ</dd><small>وتظهر أيضًا كتابة: المهندس اسلام الشيخ · اسلام الشيخ</small></div><div dir="ltr"><dt>Professional name in English</dt><dd>Eslam Elshikh</dd><small>Also written: Islam Elshikh · Eslam El Sheikh</small></div><div><dt>الاختصاص المرتبط بـ Google</dt><dd>إسلام الشيخ — خبير منتجات Google</dd><small><a href="/google-expert/">صفحة الخبرة</a> · <a href="${site.social.googleDeveloper}" target="_blank" rel="noopener">ملف Google للمطورين ${icon("external")}</a></small></div></dl></div></section>
<section class="section-pad about-manifesto-section"><div class="container about-manifesto"><div class="about-section-marker reveal"><span>01</span><small>الرؤية الهندسية</small></div><div class="about-manifesto-copy reveal">${eyebrow("الصورة الكاملة أولًا")}<h2>أعالج أصل المشكلة، لا الضجيج الذي تصنعه أعراضها.</h2><p class="about-lead">المشكلة الرقمية لا تسكن طبقةً واحدة. بطء الموقع قد يبدأ من المحتوى أو الاستضافة أو القياس، وضعف الظهور قد يصنعه خلل في تجربة الجوال أو بيانات الملف التجاري قبل أن يكون أزمة كلمات مفتاحية.</p><div class="about-story-columns"><p>لذلك لا أرى الموقع واجهةً وحسب، ولا الأمن فحصًا منفصلًا، ولا الذكاء الاصطناعي استعراضًا تقنيًا. أقرأ المستخدم والبيانات والصلاحيات والبنية والهدف التجاري معًا، ثم أضع الجهد حيث يصنع أثرًا حقيقيًا.</p><p>أعمل من الرياض مع أصحاب أعمال وفرق داخل السعودية وخارجها. يبدأ كل تعاون بسؤالٍ واضح، ونطاقٍ محدد، ومخرجاتٍ قابلة للمراجعة، ومعيار نجاح يفرّق بين ما نملكه ونقيسه وما تحكمه منصة أو جهة خارجية.</p></div></div><blockquote class="about-quote reveal">${icon("quote")}<p>الهندسةُ الحقّة لا تتباهى بذكائها؛ بل تُبصر موضع الخلل، وتصون الثقة، وتُشيّد من الوضوح أساسًا يثبت اليوم ويتّسع للغد.</p><span>— Eslam Elshikh</span></blockquote></div></section>
<section class="section-pad muted-section about-journey-section"><div class="container about-journey-grid"><div class="about-journey-intro reveal">${eyebrow("الأساس والخبرة")}<h2>تعليمٌ يؤسّس، وتجربةٌ تختبر، ومشروعاتٌ تُثبت.</h2><p>من أمن المعلومات إلى تطوير البرمجيات وتجربة المستخدم ومنتجات Google، لم تكن المسارات جزرًا متباعدة؛ بل طبقات صنعت عقلًا يرى المشروع من زواياه المختلفة، من دون أن يضيّع غايته.</p><div class="about-journey-seal" aria-hidden="true"><span>ENGINEERING</span><strong>360°</strong><small>MINDSET</small></div></div><ol class="about-journey-rail"><li class="reveal"><span>01</span><div><small>ACADEMIC FOUNDATION</small><h3>بكالوريوس أمن المعلومات</h3><p>كلية الحاسبات والمعلومات · جامعة 6 أكتوبر</p></div><b>CYBERSECURITY</b></li><li class="reveal"><span>02</span><div><small>ADVANCED STUDY</small><h3>دبلوم الأمن السيبراني</h3><p>الجامعة العربية المفتوحة · الرياض</p></div><b>SECURITY</b></li><li class="reveal"><span>03</span><div><small>APPLIED ENGINEERING</small><h3>برمجيات وتجارب رقمية</h3><p>تطوير مواقع وتطبيقات، وتصميم واجهات، وسيو تقني اختبرتها مشروعات منشورة.</p></div><b>SOFTWARE</b></li><li class="reveal"><span>04</span><div><small>PRODUCT COMMUNITY</small><h3>خبير منتجات Google</h3><p>مساهمة عملية في مساعدة المستخدمين وفهم تحديات الملفات التجارية وخرائط Google.</p></div><b>GOOGLE</b></li></ol></div></section>
<section class="section-pad about-focus-section"><div class="container"><div class="about-heading-row reveal"><div>${eyebrow("مجالات التخصص")}<h2>أربعة مسارات، وعقلٌ هندسي واحد.</h2></div><p>الأمن السيبراني، وتطوير المواقع والبرمجيات، ووكلاء الذكاء الاصطناعي، وخبرة Google والسيو المحلي: تختلف الأدوات، ويبقى المنهج واحدًا—تشخيص قبل التنفيذ، وحدود واضحة، ونتيجة يمكن مراجعتها وقياسها.</p></div><div class="about-focus-shell reveal" data-about-focus><div class="about-focus-tabs" role="tablist" aria-label="مجالات خبرة إسلام الشيخ">${focusTabs}</div><div class="about-focus-stage">${focusPanels}</div></div></div></section>
<section class="section-pad muted-section about-proof-section"><div class="container"><div class="about-proof-heading reveal"><div>${eyebrow("الدليل العملي")}<h2>الدليل أبلغ من الادعاء: أعمالٌ منشورة وأرقامٌ تُفتح للمراجعة.</h2></div><div class="about-proof-actions">${button("/projects/", "استعرض المواقع", "button-ghost")}${button("/google-maps-projects/", "استعرض أعمال الخرائط")}</div></div><div class="about-proof-strip reveal"><article data-code="GBP / VERIFIED"><strong data-counter="472">472</strong><span>ملفًا تم دعم توثيقه</span><small>ملفات Google التجارية</small></article><article data-code="GBP / SOLVED"><strong data-counter="233">233</strong><span>مشكلة تمت معالجتها</span><small>حالات ملفات تجارية متنوعة</small></article><article data-code="MAPS / PUBLIC"><strong data-counter="${mapsCount}">${mapsCount}</strong><span>نموذج خرائط منشور</span><small>روابط عامة قابلة للفتح</small></article><article data-code="WEB / LIVE"><strong data-counter="${projectCount}">${projectCount}</strong><span>مشروع ويب حيًا</span><small>نماذج منشورة ضمن معرض الأعمال</small></article></div><section class="about-case-evidence" aria-labelledby="about-case-evidence-title"><div class="about-case-heading reveal"><div><span dir="ltr">SELECTED CASES / ${String(caseStudyProjects.length).padStart(2, "0")}</span><h3 id="about-case-evidence-title">مشروعاتٌ تكشف كيف تتحول الفكرة إلى قرارٍ وتصميمٍ ونظام.</h3></div><p>تعرض كل دراسة الهدف والنطاق والقرارات والمخرجات التي يمكن فتحها ومراجعتها، من دون اختلاق أرقام زيارات أو تحويلات لم تُنشر بياناتها.</p></div><div class="about-case-grid">${caseStudyCards}</div></section></div></section>
<section class="section-pad about-method-section"><div class="container about-method-grid"><div class="about-method-intro reveal">${eyebrow("منهج التنفيذ")}<h2>من السؤال الأول إلى ما بعد الإطلاق: لكل خطوة معنى، ولكل قرار معيار.</h2><p>لا أبدأ من اسم التقنية، بل من القرار الذي نريد أن يصبح ممكنًا؛ ثم أبني أقصر طريق مسؤول إليه، وأترك خلفي نظامًا مفهومًا لا صندوقًا مغلقًا.</p>${button(`${site.whatsapp}?text=${encodeURIComponent("مرحبًا م. إسلام، أرغب في مناقشة مشروعي ومعرفة نقطة البداية المناسبة.")}`, "ناقش نقطة البداية", "", true)}</div><ol class="about-method-list"><li class="reveal"><span>01</span><div><h3>أقرأ السياق قبل أن أقترح الحل</h3><p>أفهم الهدف والمستخدم والوضع الحالي والقيود والاعتماديات وما جُرّب من قبل.</p></div></li><li class="reveal"><span>02</span><div><h3>أحوّل الهدف إلى نطاق وقرار</h3><p>أحدّد الأولويات والمخرجات ومعايير القبول قبل اختيار الأدوات أو رسم الواجهة.</p></div></li><li class="reveal"><span>03</span><div><h3>أبني على مراحل تُختبر</h3><p>أنفّذ في دورات قصيرة، وأوثّق القرارات، وأراجع الأمان والأداء والتجربة.</p></div></li><li class="reveal"><span>04</span><div><h3>أسلّم نظامًا يُفهم ويُقاس</h3><p>تسليم واضح وخطة تشغيل وقياس، ثم تحسين تقوده البيانات لا التخمين.</p></div></li></ol></div></section>
<section class="section-pad muted-section about-standards-section"><div class="container"><div class="section-heading reveal">${eyebrow("مبادئ التعاون")}<h2>الثقة تبدأ بما أقوله بوضوح—وتكتمل بما أرفض أن أعد به.</h2><p>هذه الحدود ليست هامشًا قانونيًا؛ إنها الطريقة التي أصون بها قرارك وبياناتك وجودة ما يُسلَّم إليك.</p></div><div class="about-standards-panel reveal"><section><span class="about-standard-label is-positive">${icon("check")}ألتزم به</span><ul><li>نطاق ومخرجات ومعيار نجاح يمكن مراجعته</li><li>احترام البيانات والصلاحيات وحدود الوصول</li><li>قرار تقني يمكن شرحه وصيانته بعد التسليم</li><li>وضوح في المخاطر والاعتماديات وما يحتاج متابعة</li></ul></section><section><span class="about-standard-label">${icon("close")}لن أعدك به</span><ul><li>ترتيب مضمون في Google أو قرار من منصة خارجية</li><li>وصول غير ضروري إلى الحسابات أو كلمات المرور</li><li>حل معقد لمجرد أنه يستخدم تقنية أحدث</li><li>نتائج غير قابلة للقياس أو ادعاءات بلا دليل</li></ul></section></div></div></section>
${finalCta("إذا كان مشروعك يحتاج عينًا ترى الصورة كاملة، فلنبدأ من السؤال الصحيح.", "أرسل الهدف والوضع الحالي والروابط المتاحة؛ نحدّد أصل المشكلة، والنطاق الذي يستحق التنفيذ، والخطوة التالية بوضوح.")}`;
}
