// Design interpretation of the visible content routes, not commercial performance claims.
const rules = [
  [/جهات الاتصال|ملف العميل/, "ملف الاتصال هو نقطة ربط الطلب بالسياق: من صاحب الطلب، وما احتياجه، وأي متابعة تخصه. وضعه كوحدة واضحة يجعل العلاقة بين الشاشات مفهومة.", "The contact record gives a request its context: who it belongs to, what they need, and which follow-up relates to it. A defined module makes that connection understandable."],
  [/المواعيد|المتابعات|برقم ورمز/, "تحتاج المتابعة إلى حالة يمكن الرجوع إليها وخطوة تالية محددة. إبراز هذا المسار يوضح كيف يستمر العمل بعد استقبال الطلب الأول.", "Follow-up needs a reviewable status and a defined next step. This route explains how work continues after the first request."],
  [/التقارير|صلاحيات/, "العمل التشغيلي وقراءة الملخصات وظيفتان مختلفتان. هذا الجزء يوضح مكان التقرير أو الدور داخل المنظومة، بدل عرض كل المعلومات كقائمة واحدة.", "Operational work and reading summaries are different tasks. This module explains the place of reporting or roles within the system."],
  [/SAP/, "جولة الاستيراد تحول موضوع البيانات إلى خطوات يمكن مناقشتها: مصدر الملف، وأعمدته، والتحقق، والمراجعة. يظل هذا المسار جزءًا من تصور المنتج المقترح.", "The import walkthrough makes data handling tangible through file source, columns, validation, and review. It remains part of the proposed product concept."],
  [/الأطباء|عيادات/, "في الدليل، يبدأ هذا المسار بنوع التخصص الذي يبحث عنه المستخدم. اسم الفئة يضع المعلومة في سياقها المحلي، ويساعد على فصلها عن بقية الخدمات اليومية.", "In a directory, this route starts with the service type the visitor needs. The category gives the information a local context distinct from other everyday services."],
  [/الصيدليات|صيدليات/, "فئة مستقلة لاحتياج يومي محدد داخل الدليل. التنظيم بحسب نوع النشاط يجعل العثور على المعلومة أقرب إلى طريقة السؤال عنها.", "A dedicated category for a specific everyday need. Organizing by business type follows the way people ask for local information."],
  [/مدارس|معاهد|المحلات/, "التصنيف يعطي الأنشطة المتشابهة مدخلًا مشتركًا داخل المنصة. يستطيع الزائر البدء بالمجال الذي يحتاج إليه قبل مراجعة تفاصيل الجهة.", "A category gives related establishments a shared entry point. Visitors can begin with the field they need before inspecting a particular listing."],
  [/مدينة الوقف|المراشدة|القلمينا/, "المكان نفسه هو مدخل التصفح هنا. ربط التصنيف بالمنطقة يحافظ على علاقة الخدمة بالنطاق الجغرافي الذي يبحث فيه المستخدم.", "The place itself is the entry point. An area-based category keeps services connected to the geographic context of the search."],
  [/الذكاء الاصطناعي/, "المسار يجمع الخدمات تحت مهمة تقنية مفهومة. يساعد هذا التقسيم على شرح أين يدخل الذكاء الاصطناعي في العمل، قبل الانتقال إلى تفاصيل الحل المطلوب.", "This route groups technical services around an understandable task, explaining where AI fits before discussing a particular solution."],
  [/المنتجات الرقمية/, "فصل المنتجات الرقمية عن بقية الخدمات يعطي تصميم المنتج وتنفيذه مساحة شرح خاصة، داخل هوية الشركة التقنية.", "A dedicated digital-product route gives product design and implementation their own explanation within the company's technical identity."],
  [/منظومة Google/, "حضور Google والنمو لهما مسار يشرح علاقتهما بالنشاط. التقسيم يساعد على تمييز هذا العمل عن تطوير المنتج أو بناء الأتمتة.", "The Google and growth route explains its relationship to the business, separately from product development and automation."],
  [/الرنين|الموجات|الدوبلر|الحجامة/, "تقديم نوع الفحص أو الخدمة باسمه يوضح ما الذي يحتاج الزائر إلى الاستفسار عنه. هذه خطوة لتنظيم رحلة المعلومة والزيارة، وتبقى التفاصيل المهنية لدى المركز.", "Naming the examination or service clarifies what a visitor needs to ask about. This organizes the information and visit journey; professional details remain with the center."],
  [/غرف عبايات|غرف ملابس|دريسنج/, "نوع المساحة يحدد طريقة التفكير في التخزين. الفئة تساعد العميل على وصف غرفة كاملة وتوزيعها، بدل الاكتفاء بطلب قطعة أثاث عامة.", "The space type shapes the storage brief. This category helps visitors describe an entire room and its layout rather than a generic furniture request."],
  [/خزائن|دواليب/, "الفئة تربط التخصص باحتياج التخزين. المقاس والاستخدام والتقسيم الداخلي تصبح نقاطًا مفيدة للنقاش حول القطعة المطلوبة، بدل البدء بسؤال عام عن النجارة.", "This category connects the craft to a storage need. Measurements, use, and internal divisions become useful discussion points for the intended piece."],
  [/غرف نوم|غرف النوم|غرف أطفال/, "التفصيل هنا مرتبط بغرفة واستخدامها، لا بقطعة منفصلة فقط. إظهار الفئة يساعد على وصف المساحة والأثاث الذي يريد العميل مناقشته.", "Custom work is linked to a room and its use. The category helps visitors describe the space and furniture they want to discuss."],
  [/ديكور|تكسيات|جبس|فوم|الجدران/, "هذا المسار يخاطب شكل المساحة وتشطيبها. عرضه كفئة مستقلة يساعد على مناقشة النمط والمكان والأمثلة المناسبة قبل تحديد نطاق التنفيذ.", "This route concerns the appearance and finishing of a space. A distinct category supports discussion of style, location, and relevant examples before defining scope."],
  [/نوافذ|شبابيك|درايش|أبواب|واجهات|قواطع|زجاج|الشتر/, "اسم الفئة يحدد الجزء المطلوب من المبنى أو المساحة. يبدأ النقاش بالمقاس والاستخدام ونوع العنصر، بدل جمع أعمال الألمنيوم والزجاج تحت وصف واحد.", "The category identifies the relevant part of a building or space. Dimensions, use, and component type give the enquiry a more specific starting point."],
  [/تسرب|الصرف|المجاري|المواسير/, "يبدأ المستخدم من المشكلة التي يعرفها: تسرب أو صرف أو شبكة مياه. تسمية الحالة تربط لغة البحث اليومية بالتخصص الذي يحتاج إلى مناقشته مع الفني.", "Visitors start with the problem they recognize: a leak, drain, or water network. The category links everyday search language with the relevant technical enquiry."],
  [/الإنارة|الكهرباء|كهرباء|كهربائي|أسلاك|كهربائية/, "الفئة توضح جانب العمل الكهربائي أو الإنارة داخل العرض. تساعد الزائر على التمييز بين احتياج تأسيس وتركيب أو سؤال عن صيانة ومستلزمات.", "The route clarifies electrical or lighting work within the offering, helping visitors distinguish installation needs from maintenance or supply enquiries."],
  [/السباكة|سباكة|سباك|الأدوات الصحية|الخلاطات|السخانات|المضخات/, "هذا المسار يمنح احتياج المياه أو الأدوات الصحية اسمًا مباشرًا. يوجه السؤال إلى الجزء المطلوب، مع ترك تحديد الأعمال الفنية بعد وصف الحالة ومراجعتها.", "This route gives water or sanitary-fixture needs a direct label. It guides the enquiry while technical scope follows a review of the described situation."],
  [/الدهانات|دهانات|طلاء|معجون|ورق جدران/, "تسمية نوع التشطيب تربطه بالمكان المراد العمل عليه. يساعد ذلك على نقاش المساحة واللون وحالة السطح قبل الاتفاق على العمل.", "The finishing type is tied to the intended location. It provides a starting point for discussing area, color, and surface condition."],
  [/تكييف|مكيفات|المكيفات|فريون/, "نوع الجهاز أو مهمة الصيانة يعطي الاستفسار نقطة بداية مفيدة. يسهل وصف الوحدة والمشكلة التي يريد العميل مراجعتها، دون افتراض تشخيصها من الصفحة.", "The unit type or maintenance task gives the enquiry a useful starting point, without assuming the website can diagnose a fault."],
  [/البناء|بناء|مقاولات|تسليم مفتاح|ترميم|التشطيبات/, "الفئة تميز نوع العمل داخل مشروع أوسع. يمكن للزائر البدء بالبناء أو التجديد أو التشطيب الذي يخصه، ثم مناقشة الموقع والنطاق المناسب.", "The category distinguishes a work type within a larger project, giving visitors a route into construction, renovation, or finishing discussions."],
  [/مظلات|سواتر|ساندوتش/, "هذه الأعمال مرتبطة بمساحة واستخدام واضحين. إظهارها منفصلة يساعد على وصف الموقع والحجم والغرض قبل مناقشة تفاصيل التصميم والتنفيذ.", "These works are tied to a specific space and use. Separate categories help visitors describe location, scale, and purpose before discussing execution."],
  [/تنظيف|النظافة/, "التنظيف يُعرض باعتباره نطاق عمل له مكان ونوع احتياج. الفئة تساعد على وصف المنشأة أو الأثاث المطلوب التعامل معه بدل طلب خدمة عامة بلا تفاصيل.", "Cleaning is presented as a scope with a location and need type, helping visitors describe the facility or furnishings involved."],
  [/الصيانة الفنية|وصف منظم|توجيه حسب/, "الطلب يحتاج تفاصيل قابلة للفهم قبل تنسيقه أو إسناده. هذا المسار يوضح العلاقة بين الخدمة والمكان والخطوة التالية في استقبال الاحتياج.", "A request needs understandable details before coordination or assignment. This route connects the service, location, and next intake step."],
  [/ساعات العمل|موقع المتجر|الاتجاهات/, "معلومة عملية تساند التخطيط للزيارة. وجودها في موضع واضح يربط التعريف بالنشاط بمعرفة متى وأين يبدأ التواصل أو الوصول.", "Practical information supports visit planning and connects the business introduction with when and where to make contact or arrive."],
  [/الاستفسار|نموذج التواصل|وسائل التواصل|نطاق الخدمة/, "هنا تنتقل التجربة من التعريف إلى السؤال عن حالة محددة. وضوح وسيلة التواصل أو نطاق الخدمة يساعد الزائر على إعداد تفاصيل طلبه.", "This route moves the experience from introduction to a specific enquiry. Contact or coverage information helps visitors prepare their request."],
  [/مستلزمات|مواد البناء/, "عرض المستلزمات في فئة واضحة يميز الاستفسار عن المنتج من طلب التنفيذ. يستطيع العميل تحديد الصنف أو الفئة التي يريد السؤال عنها.", "A defined supplies category distinguishes product enquiries from execution requests and helps visitors identify the item they need."],
  [/الترافع|الاستشارات|التوثيق/, "فئة مهنية توضح نوع المسألة التي يريد الزائر مناقشتها مع المكتب. فصل التخصصات يعطي بداية منظمة للاستفسار دون افتراض نتيجة قانونية.", "A professional category clarifies the matter a visitor wants to discuss, without assuming a legal outcome."],
  [/الأفراد والأعمال|العمالة|الاستقدام/, "المسار يميز جمهور الطلب أو فئته داخل خدمات المكتب. التنظيم يساعد على فهم الاختيارات المطروحة قبل مناقشة التفاصيل والمتطلبات مع الجهة.", "This route identifies the audience or request category within the office's services before the visitor discusses details and requirements."],
  [/باقة|الصبار|طاولات/, "الصورة واسم العنصر يحولان فكرة الهدية أو التنسيق إلى اختيار محدد. تصبح المناسبة ونوع التنسيق نقطتي بداية لمناقشة التفاصيل.", "The item name and visual presentation turn a gift or arrangement idea into a specific option to discuss."],
  [/حدائق|البستنة|العشب|عشب/, "هذه الفئة تربط التنسيق بعناصر المكان. يستطيع العميل وصف المساحة والعناصر التي يريد مناقشتها، بدل البدء بوصف عام لحديقة كاملة.", "This category connects landscaping to the elements of a place, helping visitors describe the space and the parts they want to discuss."],
  [/مطابخ|المطابخ/, "التخصص مرتبط بالاستخدام اليومي وتقسيم المساحة. إبرازه منفصلًا يساعد على وصف المقاسات والتوزيع قبل مناقشة الخامات والتنفيذ.", "The route connects daily use with spatial layout, giving measurements and organization a place in the discussion before materials and execution."],
  [/نجارة|نجار|صيانة|تركيب|تجديد/, "يعرض هذا الجزء جانبًا محددًا من العمل الحرفي أو الصيانة. وجوده داخل بنية المحتوى يتيح وصف القطعة أو الجزء المراد مراجعته مع النشاط.", "This section identifies a particular craft or maintenance need so visitors can describe the relevant piece or component." ]
];
export function describeCaseScope(topic, english = false) {
  const rule = rules.find(([pattern]) => pattern.test(topic));
  return rule ? rule[english ? 2 : 1] : english
    ? "A defined content route gives this part of the offering a clear place within the experience and a specific starting point for an enquiry."
    : "مسار محتوى له مكان واضح داخل التجربة، يعطي هذا الجزء من العرض اسمًا يمكن للزائر الرجوع إليه عند وصف احتياجه.";
}
