const pair = (ar, en) => ({ar, en});
const qa = (questionAr, questionEn, answerAr, answerEn, topic) => ({question:pair(questionAr,questionEn),answer:pair(answerAr,answerEn),topic});
export const crmQuestions = {
  'sama-scan-control-center': [
    qa('كيف يمنع CRM سما سكان ضياع سياق طلب الفحص؟','How does Sama Scan CRM preserve an examination request’s context?','يرتبط الطلب بجهة الاتصال ونوع الفحص والمصدر والحالة والمسؤول. يستطيع الاستقبال معرفة آخر خطوة وما يحتاج متابعة، بدل إعادة جمع المعلومات من محادثات متفرقة. الفائدة التنظيمية تعتمد على تحديث الفريق للسجل باستمرار.','The request links contact, examination, source, stage and owner. Reception can see the last action and next follow-up without rebuilding context from separate conversations. Staff must keep records current.','daily'),
    qa('هل طلب الموقع يعني أن الموعد تأكد؟','Does a website request confirm an appointment?','طلب الموقع بداية للمراجعة. يتولى الاستقبال تنسيق مورد الفحص والوقت وتسجيل التأكيد، ثم الحضور أو الإلغاء. فصل هذه المراحل يساعد الفريق على قراءة الطلبات والمواعيد والحضور بدقة.','A website request starts the review. Reception arranges the resource and time, records confirmation, then attendance or cancellation. Separating these stages makes request, appointment and attendance figures understandable.','daily'),
    qa('كيف تتوزع المتابعات بين الاستقبال والإدارة؟','How are follow-ups shared between reception and management?','تُسند المهام لمسؤول مع موعد استحقاق وأولوية وحالة إنجاز. توجد مساحات بحسب الدور وسجل تعديلات؛ تُضبط الصلاحيات وفق مهام الفريق، ويُراجع نطاق الوصول أثناء إعداد النظام.','Tasks have an owner, due date, priority and completion state. Role-based workspaces and an audit trail support coordination; access is configured against team responsibilities during setup.','connections'),
    qa('ما علاقة المركز بالأطباء المحيلين داخل التجربة؟','How are referring-physician relationships represented?','يتضمن النطاق الإداري مساحة للأطباء المحيلين والزيارات والمتابعات والتقارير. فائدتها حفظ سياق العلاقة والخطوة القادمة، إلى جانب متابعة طلبات المركز اليومية، وفق البيانات التي يسجلها الفريق.','Administrative modules cover referring physicians, visits, follow-ups and reports. They preserve relationship context and next actions alongside daily center requests, based on the records entered by the team.','connections'),
    qa('هل هو نظام أشعة أو سجلات تشخيصية؟','Is this a radiology or diagnostic-record system?','النطاق المعروض لإدارة العمل الإداري والطلبات والمواعيد والمتابعات. لا تشمل هذه التجربة صور الأشعة أو التقارير التشخيصية أو الفوترة، ولا تعرض الجولة سجلات مرضى حقيقية.','This scope covers administration, requests, appointments and follow-ups. The walkthrough excludes radiology images, diagnostic reporting and billing, and does not expose real patient records.','scope'),
    qa('ما الذي أثبته الجولة قبل طلب نظام مشابه؟','What can I assess before commissioning a similar system?','يمكنك مراجعة الواجهة ورحلة الطلب وأدوار الوحدات. البيانات توضيحية؛ لا تثبت أعداد حجوزات أو نتائج تشغيل فعلية. يبدأ التنفيذ المشابه بتحديد مصادر الطلب وموارد المواعيد والصلاحيات ومعايير قبول كل مرحلة.','Inspect the interface, request journey and module roles. Demonstration records do not prove booking volumes or operating outcomes. A similar build starts with sources, appointment resources, permissions and acceptance criteria.','scope')
  ],
  'alargan-crm': [
    qa('كيف يشرح تصور الأرجان CRM رحلة العميل العقاري؟','How does the ALARGAN CRM concept explain a property customer’s journey?','يجمع التصور هوية العميل واحتياجه والمشروع أو الوحدة والفرصة والخطوة القادمة. يساعد فريق المبيعات على مناقشة أين تبدأ العلاقة وكيف تتحرك، قبل اعتماد متطلبات بناء النظام التشغيلي.','The concept connects identity, need, project or unit, opportunity and next action. It helps sales teams discuss how a relationship starts and moves before agreeing operational-system requirements.','daily'),
    qa('لماذا نجرب المسار قبل تطوير منصة مبيعات؟','Why explore the workflow before building a sales platform?','المعاينة تجعل الأسئلة محددة: من يملك الفرصة؟ وما المرحلة التالية؟ وما البيانات اللازمة؟ يمكن مناقشة السيناريوهات واعتماد النطاق قبل البرمجة. هذه فائدة لتوضيح المتطلبات، وليست نتيجة مبيعات مقاسة.','The preview makes requirements concrete: who owns an opportunity, what happens next, and which data is needed? Teams can discuss scenarios before development. This is a requirements benefit, not a measured sales result.','daily'),
    qa('هل الربط المقترح مع SAP مباشر وحي؟','Is the proposed SAP connection live and direct?','المسار المعروض قائم على ملفات Excel أو CSV: تصدير، رفع، مطابقة الأعمدة، فحص الفروق ومراجعة بشرية. ليس اتصالًا حيًا مباشرًا بـSAP. أي تكامل أوسع يحتاج اعتمادًا تقنيًا ونطاقًا مستقلًا.','The proposed flow uses Excel or CSV files: export, upload, column mapping, difference checks and human review. It is not a direct live SAP connection. Broader integration needs separate technical assessment and scope.','connections'),
    qa('كيف تُناقش الصلاحيات وقنوات التواصل؟','How are permissions and communication channels scoped?','توضح الجولة ارتباط التواصل بالعميل والفرصة، لتحديد من يحتاج قراءة البيانات أو تعديلها وما يجب تسجيله. الصلاحيات والتكاملات التشغيلية تُعتمد ضمن متطلبات التنفيذ، وليست خدمة تشغيل مضمونة في هذا التصور.','The tour shows communication in customer and opportunity context, helping define who reads or edits records and what should be logged. Operational access and integrations are agreed during delivery scoping.','connections'),
    qa('هل الأرجان منصة تشغيل منفذة أم تصور؟','Is ALARGAN an operational platform or a concept?','التجربة المعروضة تصور منتج وعرض تفاعلي ببيانات توضيحية. ليست منصة مبيعات تشغيلية منشورة. الوظائف المقترحة تساعد على اعتماد النطاق، ولا تُعرض كإثبات لتشغيل لدى العميل.','The published experience is an interactive product concept with illustrative data, not a deployed operational sales platform. Proposed capabilities support scope discussions and are not proof of client operation.','scope'),
    qa('ما الخطوة التالية إذا أعجبتني الفكرة؟','What comes next if the concept fits my needs?','نحدد الفريق ومراحل البيع ومصادر البيانات ونطاق استيراد الملفات، ثم نعتمد نموذج البيانات والصلاحيات واختبارات القبول. بعدها يُحدد عرض التنفيذ والتسليم بناءً على متطلبات نشاطك.','Define the team, sales stages, sources and file-import scope; agree the data model, permissions and acceptance tests. Delivery and pricing then follow your business requirements.','scope')
  ],
  'tawod-control-center': [
    qa('كيف تجمع لوحة تعاود التسويق والمتابعة؟','How does Tawod connect marketing and follow-up?','تضع اللوحة مصادر التواصل والعملاء والفرص والمتابعات في سياق واحد. يستطيع المسؤول ربط مصدر الطلب بمرحلته والخطوة القادمة، مع قراءة القياس وفق مصدره وتاريخ تحديثه.','The workspace brings contact sources, customers, opportunities and follow-ups into one context. Owners can connect a source to its stage and next action while checking measurement origin and freshness.','daily'),
    qa('هل ضغطة واتساب أو الاتصال تعني عميلًا أو عقدًا؟','Does a WhatsApp or call click mean a customer or contract?','لا. تميز التجربة بين إحالة التواصل والمكالمة المستلمة والفرصة المؤهلة والعقد المسجل. هذا الفصل يساعد الإدارة على معرفة ما تم قياسه فعلًا، ويحتاج توثيق المراحل اللاحقة داخل متابعة الفريق.','No. The experience separates a contact referral, a received call, a qualified opportunity and a recorded contract. Later stages depend on team follow-up records; a click alone does not establish them.','daily'),
    qa('كيف تدخل بيانات Google Ads والملف التجاري؟','How do Google Ads and Business Profile data enter the system?','توجد وحدات للمصادر مع توضيح مصدر القياس ووقت المزامنة. تشغيل الربط يحتاج الإعداد والصلاحيات المناسبة؛ لا تصبح حسابات نشاط جديد متصلة لمجرد فتح الجولة العامة.','Source modules identify measurement origin and sync time. Live connections require appropriate setup and permissions; opening the public tour does not connect a new business’s accounts.','connections'),
    qa('هل يمكن مراجعة بيانات التواصل الاجتماعي أيضًا؟','Can social reporting be reviewed too?','تدعم التقارير الاستيراد بحسب المصدر المتاح ضمن نطاق النظام. يُتفق على تنسيق البيانات ودوريتها وطريقة مطابقتها، حتى تُقرأ بجانب المصادر الأخرى دون خلط مؤشرات مختلفة.','Reports support imports according to available sources. Format, refresh schedule and reconciliation are agreed so information can be reviewed without mixing different metric definitions.','connections'),
    qa('هل أرقام الجولة هي نتائج تعاود الحقيقية؟','Are the tour’s figures Tawod’s actual results?','الجولة تستخدم بيانات عرض ولا تنشر بيانات النشاط الفعلية أو تفاصيل حسابات العميل. فائدتها توضيح الشاشة وسير العمل؛ تقييم أداء الحملات يحتاج تقارير حسابات مؤرخة وقياسًا مستقلًا.','The tour uses presentation data and does not publish actual company performance or account details. Campaign evaluation requires dated account reports and separate measurement.','scope'),
    qa('كيف يُبنى نظام مماثل لشركة مقاولات؟','How is a similar contracting system scoped?','نبدأ بمصادر الطلب والخدمات وأدوار الفريق ومراحل الفرص. بعدها نحدد ما يتصل بالموقع أو المصادر الإعلانية، وكيف تُسجل المتابعة والنتيجة، وما يحتاجه المدير لاتخاذ قرار واضح.','Start with enquiry sources, services, team roles and opportunity stages. Then define website or advertising connections, follow-up and outcome records, and the information managers need for decisions.','scope')
  ],
  'kermez-control-center': [
    qa('هل يستطيع الفريق تحديث المنيو من الإدارة؟','Can staff update the public menu from administration?','يمكن تعديل اسم الصنف وتصنيفه وصورته ووصفه وسعره وتوفره، مع أرشفته أو استعادته ونشر التحديث في المنيو العام. هذا يتيح إدارة المحتوى من مسار محدد بدل تعديل صفحات الموقع يدويًا.','Staff can edit item names, categories, images, descriptions, prices and availability, archive or restore items, and publish menu changes through a defined administration flow.','daily'),
    qa('كيف تخدم أقسام النظام تشغيل المقهى؟','How do the modules support cafe operations?','يضم النطاق 11 قسمًا: ملخص اليوم والطلبات والعملاء والمنيو والمخزون والمصروفات والمهام والتقارير والفريق وسجل النشاط والإعدادات. تتيح هذه المساحات مراجعة ما يسجله الفريق من مكان منظم.','Eleven modules cover overview, orders, customers, menu, inventory, expenses, tasks, reports, team, activity and settings. They organize the information staff record for operational review.','daily'),
    qa('هل نموذج الحجز يسجل موعدًا مؤكدًا تلقائيًا؟','Does the booking form automatically create a confirmed reservation?','النموذج يجهز استفسارًا برسالة واتساب، ويحتاج رد فريق المقهى وتأكيده. لا يُدخل حجزًا تلقائيًا في مركز التشغيل ضمن النطاق الحالي؛ تسجيله داخل النظام خطوة مستقلة.','The form prepares a WhatsApp booking enquiry requiring staff response and confirmation. In the current scope it does not automatically insert a booking into the operations workspace.','connections'),
    qa('كيف تُدار صلاحيات الفريق وتحديثاته؟','How are staff access and changes managed?','توجد إدارة للفريق والصلاحيات وسجل للنشاط والإعدادات. يُحدد الوصول بحسب مسؤوليات العاملين، لتظل إدارة المنتجات والبيانات التشغيلية داخل مساحة الفريق المناسبة.','Team, role, activity and settings areas support staff administration. Access is configured against responsibilities so product and operational information stay within the appropriate workspace.','connections'),
    qa('هل أستطيع تغيير البيانات في الجولة العامة؟','Can I change records in the public demo?','الجولة العامة ببيانات توضيحية والحفظ معطّل فيها. يمكن مراجعة الواجهات لفهم العمل، بينما التشغيل الفعلي وتحديث البيانات يحتاجان دخول الفريق المصرح له إلى لوحة الإدارة.','The public walkthrough uses illustrative records and disables saving. Actual operation and changes require authorized staff access to administration.','scope'),
    qa('هل التقارير المعروضة تثبت مبيعات المقهى؟','Do the displayed reports prove cafe sales?','أرقام العرض ليست مبيعات النشاط الفعلية. التقارير تساعد على فهم طريقة قراءة السجلات داخل النظام، أما نتيجة العمل فتتحدد بالبيانات التشغيلية الحقيقية ومدى اكتمال تسجيلها.','Demo figures are not actual business sales. Reports show how records are reviewed; operational conclusions require real, complete business records.','scope')
  ],
  'alya-catalog-control': [
    qa('ما فائدة لوحة إدارة منتجات عليا؟','What does Alya’s product administration enable?','يضيف الفريق المنتجات ويعدل الاسم والصورة والوصف والسعر وحالة النشر من لوحة خاصة. تساعده على إبقاء الكتالوج مطابقًا للمحتوى الذي يعتمده دون الحاجة إلى تعديل صفحات الموقع يدويًا.','Private administration lets staff create and edit names, images, descriptions, prices and publication state, keeping the catalog aligned with approved content.','daily'),
    qa('كيف يصل الزائر إلى المنتج المناسب؟','How can visitors find a suitable product?','يضم الكتالوج بحثًا وتصنيفات وبطاقات وصفحات مستقلة للمنتجات. كان فيه 13 منتجًا منشورًا وقت مراجعة 7 أكتوبر 2026. وصف المنتج يساعد الزائر على تجهيز استفسار أكثر تحديدًا للمتجر.','Search, categories, cards and dedicated pages guide product discovery. Thirteen products were published at the 7 October 2026 review. Descriptions help visitors prepare more specific enquiries.','daily'),
    qa('هل الصور تعرض لوحة الإدارة الخاصة؟','Do the screenshots show private administration?','الصور المعروضة من الموقع والكتالوج العام. وظائف إدارة المنتجات روجعت من مصدر المشروع ودليل الاستخدام؛ تبقى لوحة الفريق الخاصة محمية ولا تُعرض كجولة إدارة عامة.','Captures show the public website and catalog. Administration capabilities were reviewed against project source and the user guide; protected staff administration is not exposed as a public tour.','connections'),
    qa('كيف ترتبط المنتجات بالخدمات ومعلومات المتجر؟','How do products relate to services and store information?','تفصل التجربة بين اكتشاف المنتجات وخدمات التنفيذ، وتعرض التواصل والخريطة وساعات العمل ببيانات متسقة مع الملف التجاري. يحصل الزائر على طريق واضح للسؤال أو الزيارة بحسب احتياجه.','The experience separates products from installation services and aligns contact details, Maps and hours with the Business Profile, giving visitors relevant enquiry and visit routes.','connections'),
    qa('هل هذه التجربة متجر بدفع إلكتروني؟','Does this experience include online payment?','النطاق المعروض كتالوج واستفسارات وإدارة محتوى. لا تتضمن الجولة دفعًا إلكترونيًا أو تأكيد طلب شراء. إضافة تجارة إلكترونية كاملة تحتاج تحديد الدفع والطلبات والشحن ضمن نطاق آخر.','The displayed scope covers catalog discovery, enquiries and content management. It does not include online payment or purchase confirmation; full ecommerce needs separate payment, order and shipping scope.','scope'),
    qa('هل لوحة المنتجات تُعد نظام CRM كاملًا؟','Is product administration a complete CRM?','هي لوحة لإدارة المنتجات والمحتوى، وليست في هذه الجولة نظامًا كاملًا لإدارة علاقات العملاء. عرضها بجانب أنظمة CRM يوضح تنوع لوحات الأعمال؛ تُضاف إدارة العملاء والفرص إذا احتاجها النشاط واعتمد نطاقها.','This is product and content administration, not a full customer-relationship system in the displayed scope. It illustrates another business-dashboard use case; customer and opportunity management can be separately scoped.','scope')
  ]
};
export const crmServiceQuestions = [
 qa('متى أحتاج نظام CRM مخصصًا؟','When does a custom CRM make sense?','عندما تحتاج ربط العملاء والطلبات والفرص والمتابعات بطريقة عمل خاصة بفريقك، وتصبح الجداول أو الأدوات الحالية عاجزة عن حفظ السياق والمسؤول والخطوة التالية. نراجع الاحتياج أولًا لتحديد ما يستحق البناء وما يمكن خدمته بأداة قائمة.','When your team needs a specific connection between customers, requests, opportunities and follow-ups that existing tools do not support well. We first review whether a custom build or an existing product best fits the workflow.','daily'),
 qa('ما الذي تحدده مرحلة تصميم النظام؟','What is decided during system design?','نحدد المستخدمين والأدوار ومراحل العمل والبيانات ومصادرها وقواعد التحقق والتكاملات المطلوبة. تُعتمد واجهات وسيناريوهات واضحة قبل التنفيذ، ثم تُختبر المهام الأساسية على الجوال وسطح المكتب وفق نطاق التسليم.','Users, roles, stages, data, sources, validation and integrations are agreed through interfaces and scenarios. Core tasks are then tested on mobile and desktop against the delivery scope.','connections'),
 qa('كيف تتحدد تكلفة تطوير CRM ولوحة التحكم؟','How is a custom CRM or dashboard priced?','بحسب عدد الوحدات وتفاصيل سير العمل والصلاحيات والتكاملات وترحيل البيانات والدعم المطلوب. يُفصل عرض التنفيذ عن رسوم الاستضافة والخدمات الخارجية المتكررة؛ لا تكفي صورة لوحة لتحديد سعر عادل.','By modules, workflow detail, permissions, integrations, migration and support. Implementation is distinguished from recurring hosting and external-service costs; a screenshot alone cannot establish a fair price.','scope'),
 qa('هل يمكن ربط النظام بموقعي وأدوات القياس؟','Can the system connect to my website and measurement tools?','يُراجع كل مصدر على حدة لتحديد إمكان الربط والصلاحيات ودورية التحديث. قد يكون المسار نموذج طلب أو تكاملًا أو استيراد ملفات، بحسب النظام المتاح. لا تُعرض كل التجارب كأن لها ربطًا مباشرًا واحدًا.','Each source is assessed for connection options, permissions and refresh needs. The route may be a request form, integration or file import, depending on the available system.','connections'),
 qa('هل يمكن تخصيص تجربة مشابهة لنشاطي؟','Can a similar experience be tailored to my business?','نستفيد من أنماط التشغيل المعروضة، ثم نحدد النطاق المناسب لنشاطك وفريقك. مراحل التنفيذ موضحة: أربع تجارب منفذة، وتصوّر الأرجان تفاعلي؛ كما أن لوحة عليا لإدارة المنتجات وليست CRM كاملًا.','The showcased workflow patterns guide a new scope for your team. Four experiences are implemented and ALARGAN is an interactive concept; Alya is product administration rather than a complete CRM.','scope')
];
export const crmServiceAr = {slug:'crm-systems',number:'10',icon:'layers',group:'البرمجة والمنتجات الرقمية',title:'تطوير أنظمة CRM ولوحات التحكم',seoTitle:'تطوير أنظمة CRM ولوحات التحكم للشركات في السعودية | إسلام الشيخ',h1:'أنظمة CRM ولوحات تحكم تُبنى حول طريقة عملك',short:'أنظمة مخصصة لإدارة العملاء والطلبات والمتابعات، ولوحات للتشغيل والمنتجات والقياس. استكشف التجارب ومسار العمل ونطاق التنفيذ قبل مناقشة نظام يناسب فريقك.',meta:'تصميم وتطوير أنظمة CRM ولوحات تحكم للشركات في الرياض والسعودية. تجارب سما سكان وتعاود وكرمز والأرجان وعليا، مع جولات واجهات وأسئلة وأجوبة ونطاق واضح.',scope:['تصميم سير العمل ونموذج البيانات والصلاحيات','تطوير إدارة العملاء والطلبات والفرص والمتابعات','لوحات التشغيل والمنتجات والتقارير وفق النطاق','تقييم الربط بالموقع ومصادر القياس واستيراد البيانات','اختبار المهام الأساسية وتوثيق استخدام الفريق'],keywords:['تطوير CRM','لوحات تحكم للشركات','نظام إدارة العملاء','تطوير أنظمة مخصصة بالرياض'],faq:crmServiceQuestions.map(q=>[q.question.ar,q.answer.ar])};
export const crmServiceEn = {...crmServiceAr,group:'Software & Digital Products',title:'Custom CRM & Business Dashboards',seoTitle:'Custom CRM & Business Dashboard Development in Saudi Arabia',h1:'CRM and dashboards designed around your workflow',short:'Custom customer, request and follow-up systems, with operations, product and measurement dashboards. Inspect workflows and scope before commissioning a system for your team.',meta:'Custom CRM and business dashboard development in Riyadh and Saudi Arabia. Explore Sama Scan, Tawod, Kermez, ALARGAN and Alya workflows, interface tours and practical answers.',scope:['Workflow, data-model and access design','Customer, request, opportunity and follow-up modules','Scoped operations, product and reporting dashboards','Website, measurement and import assessment','Core-task testing and team handover'],keywords:['custom CRM development','business dashboards','Riyadh CRM developer'],faq:crmServiceQuestions.map(q=>[q.question.en,q.answer.en])};
export const crmPrompt = {
 'sama-scan-control-center':pair('كيف أرتب الطلبات والمواعيد؟','How do I organize requests and appointments?'),
 'alargan-crm':pair('كيف أوضح رحلة المبيعات؟','How do I map the sales journey?'),
 'tawod-control-center':pair('كيف أربط التسويق بالمتابعة؟','How do I connect marketing and follow-up?'),
 'kermez-control-center':pair('كيف أدير المنيو والتشغيل؟','How do I manage the menu and operations?'),
 'alya-catalog-control':pair('كيف يتحكم فريقي في المنتجات؟','How can staff manage product content?')
};
