// Public product stories. Screens show labelled demos or identified public sites.
const pair = (ar, en) => ({ ar, en });
export const products = [
  {
    slug: "sama-scan-control-center", code: "SAMA / 01", theme: "sama", stage: "custom", caseSlug: "sama-scan-control-center",
    name: pair("مركز عمليات سما سكان", "Sama Scan Control Center"),
    category: pair("إدارة عمليات المراكز", "Center operations"),
    headline: pair("كل طلب له مسار.<br>وكل متابعة لها مسؤول.", "Every request has a path.<br>Every follow-up has an owner."),
    description: pair("مساحة عمل عربية تربط طلبات الفحوصات بجهات الاتصال والمواعيد والمتابعات. تبدأ من الطلب القادم من الموقع، وتستمر مع فريق الاستقبال والتشغيل داخل مسار منظم.", "An Arabic workspace connecting examination requests with contacts, appointments, and follow-ups. It brings website enquiries into a structured reception and operations workflow."),
    audience: pair("الاستقبال، إدارة المركز، وفريق العلاقات والتسويق", "Reception, center managers, relationships and marketing teams"),
    problem: pair("قد يصل طلب من الموقع، ثم يُنسّق موعده ويُتابع عبر أكثر من قناة. من دون سجل مترابط يصعب معرفة المسؤول والخطوة القادمة، أو التمييز بين طلب لم يُؤكد وموعد مُعتمد.", "A website request may be scheduled and followed up through several channels. A connected record helps staff see its owner and next action, and distinguish a pending request from a confirmed appointment."),
    promise: pair("ملف واحد للطلب، وخطوة تالية واضحة للفريق.", "One connected request record. A clear next step for the team."),
    image: "/assets/products/sama-overview.webp",
    workflow: [
      pair("يصل طلب الفحص", "Examination request arrives"), pair("يراجعه الاستقبال", "Reception reviews it"),
      pair("يُنسّق الموعد", "Appointment is arranged"), pair("يُسجّل الحضور والمتابعة", "Attendance and follow-up are recorded")
    ],
    features: [
      [pair("هوية اتصال موحدة", "A unified contact record"), pair("ربط الطلبات بجهة اتصال مع توحيد الهاتف، وأرشفة السجل أو إعادة تنشيطه عند الحاجة.", "Requests connect to normalized contact records, with archiving and reactivation when needed.")],
      [pair("طلبات لها حالة ومسؤول", "Owned, staged requests"), pair("نوع الفحص ومصدر الطلب ومرحلة المتابعة والمسؤول تظهر معًا، بدل فصل المهمة عن سياقها.", "Examination type, source, stage, and owner stay together so a task retains its context.")],
      [pair("تنسيق المواعيد", "Appointment coordination"), pair("جدولة بحسب مورد الفحص، والتحقق من التعارض، ثم تسجيل التأكيد والحضور أو الإلغاء.", "Schedule by examination resource, check conflicts, and record confirmation, attendance, or cancellation.")],
      [pair("متابعة بموعد وأولوية", "Timed, prioritized follow-ups"), pair("مهام تُسنَد لأفراد الفريق مع موعد استحقاق وحالة إنجاز، وقائمة لما يحتاج اهتمامًا اليوم.", "Assign tasks with due dates, priorities, and completion status, with a view of work needing attention today.")],
      [pair("مساحات حسب الدور", "Workspaces by role"), pair("أدوار للإدارة والاستقبال والتسويق، مع سجل تعديلات ومراجعة نسخة البيانات عند التحرير.", "Administration, reception, and marketing roles, with an audit trail and version checks during editing.")],
      [pair("علاقات المركز", "Center relationships"), pair("مسارات للأطباء المحيلين والزيارات والتقارير، إلى جانب ملخصات التشغيل والتسويق.", "Referring-physician, visit, and report modules sit alongside operational and marketing summaries.")]
    ],
    tour: [
      { id: "today", label: pair("يوم العمل", "Today's workspace"), title: pair("العمل الذي يحتاج انتباهًا، في البداية.", "Start with the work that needs attention."), text: pair("تجمع الشاشة الطلبات المفتوحة والمواعيد والمهام العاجلة. ينتقل الاستقبال منها إلى سجل الطلب أو المهمة، بدل البحث بين قوائم متفرقة.", "The opening view brings open requests, appointments, and urgent tasks together. Reception can move into a request or task from this starting point."), image: "/assets/products/sama-overview.webp", points: [pair("ملخص يومي للطلبات والمهام", "Daily request and task summary"), pair("تنقل مباشر بين وحدات التشغيل", "Direct navigation across operations"), pair("مساحة مستقلة لعلاقات الأطباء", "A separate physician-relationships area")] },
      { id: "requests", label: pair("رحلة الطلب", "Request journey"), title: pair("الطلب يحتفظ بسياقه حتى بعد أول تواصل.", "A request keeps its context after first contact."), text: pair("قائمة الطلبات توضح الفحص والمصدر والمرحلة والمسؤول والخطوة القادمة. طلب الموقع يظل طلبًا يحتاج مراجعة الاستقبال؛ تأكيد الموعد يأتي داخل سير العمل.", "The request list shows examination, source, stage, owner, and next action. A website submission remains a request for reception review; appointment confirmation is a separate workflow step."), image: "/assets/products/sama-requests.webp", points: [pair("فلاتر للمرحلة والمصدر والمسؤول", "Stage, source, and owner filters"), pair("طلب ومتابعة مرتبطان بنفس الملف", "Request and follow-up share context"), pair("حجز مُنسّق وليس تأكيدًا آليًا", "Coordinated booking with staff confirmation")] }
    ],
    scope: pair("منتج مخصص منفذ لإدارة العمل الإداري بالمركز. الجولة تستخدم بيانات تجريبية. ملخصات Google المعروضة في المنتج تتضمن لقطات مؤرخة؛ وحدة المحتوى تساعد على التجهيز والمراجعة. النطاق هنا إداري، ولا يشمل صور الأشعة أو التقارير التشخيصية أو الفوترة.", "An implemented custom product for the center's administrative operations. The tour uses demonstration data. Google summaries include dated snapshots; the content module supports preparation and review. This scope is administrative and excludes radiology images, diagnostic reporting, and billing."),
    question: pair("عندك مركز يحتاج رحلة حجز ومتابعة أوضح؟", "Does your center need a clearer booking workflow?"),
    next: pair("نبدأ بمصادر الطلب، وأدوار الفريق، وموارد المواعيد، ثم نحدد الوحدات المطلوبة وطريقة الربط بالموقع.", "Start with request sources, team roles, and appointment resources, then define the necessary modules and website connection.")
  },
  {
    slug: "alargan-crm", code: "ALARGAN / 02", theme: "alargan", stage: "concept", caseSlug: "alargan-crm-concept",
    name: pair("الأرجان CRM", "ALARGAN CRM"), category: pair("تصور لمنصة مبيعات عقارية", "Property-sales platform concept"),
    headline: pair("قصة العميل كاملة.<br>قبل بناء النظام.", "The complete customer story.<br>Before the system is built."),
    description: pair("تصور تفاعلي يجمع ملف العميل والفرصة والمشروع والمتابعة في منتج واحد. يعرض رحلة المبيعات واستيراد ملفات SAP، ليصبح نقاش النطاق والوظائف مبنيًا على تجربة يمكن رؤيتها.", "An interactive concept bringing customer records, opportunities, projects, and follow-ups into one product story. Sales and SAP-file import walkthroughs make proposed scope tangible."),
    audience: pair("فرق المبيعات العقارية، الإدارة، ومسؤولو اعتماد نطاق المنتج", "Property-sales teams, managers, and product-scope decision makers"),
    problem: pair("عندما تتوزع معلومات العميل بين قنوات التواصل وملفات المشاريع والمتابعات، يصبح وصف النظام المطلوب نظريًا. العرض يحول الفكرة إلى سيناريوهات يمكن مناقشتها قبل البدء في بناء منصة تشغيل كاملة.", "When customer information spans channels, project files, and follow-ups, system requirements can stay abstract. This proposal turns the idea into scenarios that can be discussed before a full operational platform is built."),
    promise: pair("تصور يمكن تجربته ومناقشته، قبل تثبيت نطاق التنفيذ.", "A concept to explore and discuss before committing the build scope."), image: "/assets/products/alargan-pipeline.webp",
    workflow: [pair("تعريف العميل والاحتياج", "Define the customer and need"), pair("ربط المشروع والفرصة", "Connect project and opportunity"), pair("تنظيم المسؤول والمتابعة", "Define ownership and follow-up"), pair("مراجعة المسار والتقارير", "Review pipeline and reporting")],
    features: [
      [pair("ملف العميل والفرصة", "Customer and opportunity"), pair("تصور لربط هوية العميل واحتياجه بالمشروع أو الوحدة وبالخطوة القادمة.", "A proposed connection between identity, needs, project or unit, and the next action.")],
      [pair("مسار بيع قابل للشرح", "An explainable sales pipeline"), pair("مراحل للفرص وتوزيع للمسؤوليات، تظهر كيف يتقدم العمل من اهتمام أولي إلى نتيجة بيع.", "Opportunity stages and ownership illustrate progression from initial interest to a sales outcome.")],
      [pair("تنظيم قنوات التواصل", "Communication-channel context"), pair("سيناريو يوضح موقع محادثات واتساب والمتابعة داخل ملف العميل المقترح.", "A scenario showing where WhatsApp conversations and follow-ups fit within the proposed customer record.")],
      [pair("استيراد ملفات SAP", "SAP-file import concept"), pair("تصدير Excel أو CSV، ومطابقة الأعمدة، والتحقق من الفروق، ثم مراجعة بشرية قبل التحديث المقترح.", "Excel or CSV export, column mapping, difference validation, and human review before a proposed update.")],
      [pair("مساعد لشرح السيناريو", "A scenario-explanation assistant"), pair("واجهة توضح كيف يمكن للمساعد تفسير رحلة العميل والاستيراد، لدعم النقاش حول المنتج.", "An interface illustrating how an assistant could explain customer and import scenarios during product discussions.")],
      [pair("رؤية للإدارة", "A management-view concept"), pair("تصور لتقارير المراحل والفرص والمتابعة، يساعد على تحديد الأسئلة التي يجب أن يجيب عنها النظام.", "Proposed stage, opportunity, and follow-up reporting clarifies the questions the system should answer.")]
    ],
    tour: [
      { id: "customer", label: pair("العميل والفرصة", "Customer and opportunity"), title: pair("ابدأ بالعميل، ثم اتبع تفاصيل الفرصة.", "Start with the customer, then follow the opportunity."), text: pair("الواجهة التجريبية تعرض ملفًا توضيحيًا وقنوات تواصل واحتياجًا عقاريًا. الهدف من الجولة هو مناقشة شكل العلاقة بين هذه العناصر، باستخدام بيانات عرض فقط.", "The concept shows a sample record, communication channels, and a property need. The walkthrough is designed to discuss how these elements connect, using presentation data only."), image: "/assets/products/alargan-pipeline.webp", points: [pair("هوية العميل في مركز التجربة", "Customer identity at the center"), pair("قنوات تواصل مرتبطة بالسياق", "Communication linked to context"), pair("عرض تفاعلي لاعتماد المتطلبات", "An interactive requirements discussion")] },
      { id: "import", label: pair("رحلة استيراد SAP", "SAP import walkthrough"), title: pair("راجع البيانات قبل أن تنتقل إلى النظام.", "Review data before it enters the system."), text: pair("الجولة تشرح مسار الملف: تصدير، رفع، مطابقة أعمدة، فحص فروق، ومراجعة. الربط المقترح قائم على الملفات، وليس اتصالًا حيًا مباشرًا بـSAP.", "The walkthrough explains export, upload, column mapping, difference checks, and review. The proposed connection is file based, rather than a direct live SAP integration."), image: "/assets/products/alargan-import.webp", points: [pair("مصدر الملف وأعمدته واضحان", "Visible file source and columns"), pair("التحقق قبل اعتماد التحديث", "Validation before accepting updates"), pair("مراجعة بشرية ضمن المسار", "Human review within the workflow")] }
    ],
    scope: pair("تصور منتج وعرض تفاعلي، وليس منصة مبيعات تشغيلية منشورة. السيناريوهات والبيانات توضيحية، والوظائف المعروضة مقترحة. يتم اعتماد التكاملات والصلاحيات ومتطلبات التشغيل خلال تحديد نطاق التنفيذ.", "A product concept and interactive proposal, rather than a published operational sales platform. Scenarios and data are illustrative; displayed functions are proposed. Integrations, roles, and operating requirements are agreed when defining the implementation scope."),
    question: pair("هل تحتاج تحويل فكرة نظام إلى تصور واضح؟", "Need to turn a system idea into a tangible concept?"), next: pair("نرتب ورشة لفهم رحلة البيع ومصادر البيانات، ثم نبني سيناريوهات ونموذجًا تفاعليًا يساعد على اعتماد النطاق والأولويات.", "Map the sales journey and data sources in a workshop, then develop scenarios and an interactive model to agree scope and priorities.")
  },
  {
    slug: "tawod-control-center", previewKind: "scenario-interface", code: "TAWOD / 03", theme: "tawod", stage: "custom", caseSlug: "tawod-contracting",
    name: pair("مركز قيادة تعاود", "Tawod Command Center"), category: pair("التسويق والمبيعات والمتابعة", "Marketing, sales, and follow-up"),
    headline: pair("من أين جاءت الفرصة؟<br>وإلى أين وصلت؟", "Where did the opportunity start?<br>Where did it lead?"),
    description: pair("منتج مخصص يربط قياس الموقع ومصادر التسويق بملفات العملاء وفرص البيع والمتابعات. يعرض جودة البيانات وحالة مصادرها، ويُفرّق بين نقرة تواصل وفرصة مؤهلة وعقد مسجل.", "A custom product connecting website measurement and marketing sources with customer records, opportunities, and follow-ups. It distinguishes a contact click, a qualified opportunity, and a recorded contract."),
    audience: pair("إدارة الشركة، فريق التسويق، والمبيعات والمتابعة", "Company managers, marketing, sales, and follow-up teams"),
    problem: pair("عدد النقرات وحده لا يشرح جودة الطلبات أو ما حدث بعد التواصل. تحتاج الإدارة أن ترى مصدر الفرصة وحالتها والمسؤول عنها، مع معرفة مدى حداثة البيانات التي تستند إليها القرارات.", "Click counts alone do not explain lead quality or what happened after contact. Managers need the source, status, and owner of an opportunity, alongside the freshness of the data supporting a decision."),
    promise: pair("مصدر واضح، فرصة لها متابعة، وقرار يمكن تفسيره.", "A clear source, an owned opportunity, and an explainable decision."), image: "/assets/products/tawod-workspace-scenario-20261009.svg", imageSize: { width: 720, height: 1000 },
    workflow: [pair("تُقاس إحالة التواصل", "Contact referral is measured"), pair("تُراجع الفرصة وتُؤهل", "Opportunity is reviewed and qualified"), pair("تُسجّل المتابعة والعرض", "Follow-up and quote are recorded"), pair("تُراجع النتيجة ومصدرها", "Outcome and source are reviewed")],
    features: [
      [pair("ملخص تنفيذي", "Executive overview"), pair("مؤشرات للموقع والإحالات والنتائج التجارية المسجلة، مع إشارات للقرار القادم وجودة البيانات.", "Website, referral, and recorded commercial metrics, with decision signals and data-quality context.")],
      [pair("ملفات عملاء مترابطة", "Connected customer records"), pair("تجميع بيانات العلاقة والفرص السابقة والمتابعات داخل سياق عميل واحد.", "Relationship information, previous opportunities, and follow-ups stay in one customer context.")],
      [pair("مسار بيع عملي", "A practical sales pipeline"), pair("مراحل من طلب جديد إلى تأهيل وعرض ومعاينة وعقد أو فقد فرصة، مع تسجيل المسؤول والخطوة القادمة.", "Stages from new enquiry to qualification, quote, visit, contract, or loss, with owners and next actions.")],
      [pair("مصادر Google", "Google source modules"), pair("وحدات لبيانات Google Ads والملف التجاري، تعرض مصدر القياس ووقت المزامنة بدل خلطه بإجماليات الموقع.", "Google Ads and Business Profile modules identify their measurement source and sync time separately from website totals.")],
      [pair("قياس يميز المراحل", "Measurement that separates stages"), pair("فصل إحالات الاتصال وواتساب عن المكالمات المستلمة والفرص المؤهلة والعقود المسجلة.", "Separate call and WhatsApp referrals from received calls, qualified opportunities, and recorded contracts.")],
      [pair("قرارات ومتابعات", "Decisions and follow-ups"), pair("متابعات بمسؤول وموعد، وقرارات مرتبطة بمصدر ودليل، مع فحص المطابقة وحداثة البيانات.", "Owned, dated follow-ups and evidence-linked decisions, supported by reconciliation and freshness checks.")]
    ],
    tour: [
      { id: "overview", label: pair("رؤية الإدارة", "Management view"), title: pair("اقرأ الأداء ومعه سياق القرار.", "Read performance with its decision context."), text: pair("تصميم فاتح يجمع حركة الموقع والتواصل والفرص والعقود. ترى الإدارة رحلة العمل كاملة، وتنتقل من المؤشر إلى الخطوة التي تحتاج اهتمامًا.", "A light workspace brings website activity, contact, opportunities and contracts together, with a clear path from a metric to the next action."), image: "/assets/products/tawod-workspace-scenario-20261009.svg", imageSize: { width: 720, height: 1000 }, points: [pair("الإحالة والعقد مؤشران منفصلان", "Referral and contract are separate metrics"), pair("حالة المصدر ووقت تحديثه", "Source status and update time"), pair("أقسام مستقلة وتنقل واضح", "Distinct sections and clear navigation")] },
      { id: "sales", label: pair("المبيعات والمتابعة", "Sales and follow-up"), title: pair("بعد التواصل، تبدأ رحلة الفرصة.", "After contact, the opportunity journey begins."), text: pair("طلب جديد، تأهيل، عرض، معاينة، ثم عقد. مسار واضح يحفظ سياق الفرصة، ويحدد المسؤول والخطوة القادمة حتى يعرف الفريق ما يحتاج متابعة اليوم.", "New enquiry, qualification, quote, visit, then contract. A clear pipeline preserves context and gives each opportunity an owner and next action."), image: "/assets/products/tawod-sales-scenario-20261009.svg", imageSize: { width: 720, height: 1000 }, points: [pair("مراحل للفرص والعروض والعقود", "Opportunity, quote, and contract stages"), pair("موعد ومسؤول للمتابعة", "Follow-up due date and owner"), pair("نتائج تجارية من السجلات", "Commercial outcomes from records")] }
    ],
    scope: pair("منتج مخصص منفذ ضمن منظومة تعاود. تتطلب مصادر Google إعداد الربط المناسب؛ تقارير التواصل الاجتماعي تدعم الاستيراد بحسب المصدر المتاح. تبقى النقرات والمكالمات والفرص والعقود مؤشرات مختلفة داخل المنتج.", "An implemented custom product within Tawod's digital system. Google sources require the appropriate connection setup; social reports support imports according to available sources. Clicks, calls, opportunities, and contracts remain distinct metrics."),
    question: pair("هل تصل طلباتك، ثم تضيع تفاصيل متابعتها؟", "Do enquiries arrive without a clear follow-up trail?"), next: pair("نبدأ بتعريف مصادر التواصل ومراحل البيع ومسؤولية المتابعة، ثم نبني المؤشرات والواجهات على طريقة عمل فريقك.", "Define contact sources, sales stages, and follow-up ownership, then build metrics and interfaces around the team's workflow.")
  }
];
products.push(
  {
    slug: "kermez-control-center", code: "KERMEZ / 04", theme: "kermez", stage: "custom", caseSlug: "kermez-cafe",
    name: pair("مركز تشغيل كرمز", "Kermez Operations Center"), category: pair("منيو المقهى وإدارة التشغيل", "Cafe menu and operations"),
    headline: pair("المنيو أمام العميل.<br>والتشغيل أمام الفريق.", "The menu for the customer.<br>The workflow for the team."),
    description: pair("نظام مخصص يربط إدارة المنيو بعمل المقهى اليومي. يضم 11 قسمًا للطلبات والعملاء والمنتجات والمخزون والمصروفات والمهام والتقارير والفريق وسجل النشاط والإعدادات، إلى جانب ملخص اليوم.", "A custom workspace connecting menu administration with daily cafe operations. Eleven modules cover the daily overview, orders, customers, menu, inventory, expenses, tasks, reports, team, activity and settings."),
    audience: pair("إدارة المقهى، فريق التشغيل، ومسؤولو المنيو", "Cafe managers, operations staff and menu administrators"),
    problem: pair("المنيو يتغير، والطلبات تحتاج متابعة، والمخزون والمصروفات يحتاجان سجلًا واضحًا. يجمع المنتج هذه المسارات داخل واجهة عربية، مع صلاحيات للفريق وإمكانية تحديث المنيو المنشور.", "Menus change, orders need follow-up, and stock and expenses need clear records. The product brings these workflows into an Arabic workspace with staff roles and controls for the published menu."),
    promise: pair("منيو يُحدّث من الإدارة، وتشغيل له سجل ومسؤول.", "An administered menu. Recorded, owned operations."),
    image: "/assets/products/kermez-overview-20261007.webp",
    workflow: [pair("يُحدّث الفريق الصنف", "Staff update an item"), pair("يظهر في المنيو العام", "It appears in the public menu"), pair("تُسجّل الطلبات والمتابعات", "Orders and follow-ups are recorded"), pair("تُراجع بيانات التشغيل", "Operations records are reviewed")],
    features: [
      [pair("منيو من داخل الإدارة", "Menu administration"), pair("تعديل الاسم والتصنيف والصورة والوصف والسعر والتوفر، مع أرشفة الصنف واستعادته ونشر التحديث في المنيو العام.", "Edit names, categories, imagery, descriptions, prices and availability; archive or restore items and publish menu updates.")],
      [pair("الطلبات والعملاء", "Orders and customers"), pair("مساحتان مترابطتان لتسجيل الطلبات وبيانات العملاء وحالة المتابعة داخل النظام.", "Connected areas for recording orders, customer details and follow-up state.")],
      [pair("المخزون والمصروفات", "Stock and expenses"), pair("سجلات تشغيلية مستقلة للمخزون والمصروفات، بجانب ملخص اليوم والتقارير.", "Separate stock and expense records alongside the daily overview and reports.")],
      [pair("مهام وتقارير", "Tasks and reports"), pair("متابعات ومهام للفريق وشاشات تقارير تساعد الإدارة على مراجعة ما سُجل في النظام.", "Team tasks and follow-ups, with reports for reviewing the records entered in the workspace.")],
      [pair("الفريق والصلاحيات", "Team and roles"), pair("إدارة أعضاء الفريق وصلاحياتهم، مع سجل للنشاط والإعدادات.", "Manage staff and access roles, with activity and settings areas.")],
      [pair("تجربة العميل", "Customer experience"), pair("منيو مصور ببحث وستة تصنيفات، ومساعد كرموزة، ونموذج يجهّز استفسار الحجز برسالة واتساب.", "A photo menu with search and six categories, the Karmouza assistant, and a form preparing a WhatsApp booking enquiry.")]
    ],
    tour: [
      { id: "overview", label: pair("ملخص التشغيل", "Operations overview"), title: pair("صورة اليوم، قبل فتح السجلات.", "The day's picture before opening records."), text: pair("لقطة من النسخة الاستعراضية الفعلية، تجمع مداخل النظام وملخص التشغيل. الأرقام والعملاء في هذه الصورة توضيحيون، والحفظ معطّل في النسخة العامة.", "Captured from the actual public demonstration, showing module navigation and the daily overview. Its figures and customers are illustrative; saving is disabled."), image: "/assets/products/kermez-overview-20261007.webp", points: [pair("11 قسمًا في مساحة واحدة", "Eleven modules in one workspace"), pair("ملخص ومداخل للطلبات والمتابعة", "Overview and routes to orders and follow-ups"), pair("بيانات عرض موسومة بوضوح", "Clearly labelled demonstration data")] },
      { id: "menu", label: pair("إدارة المنيو", "Menu administration"), title: pair("تفاصيل الصنف تُدار من مكان واحد.", "Manage item details in one place."), text: pair("شاشة لإدارة الصور والأسماء والأسعار والتوفر. تعرض الجولة سجلات تجريبية؛ ويمكن مراجعة المنيو المنشور بصورة مستقلة من موقع كرمز.", "An interface for item imagery, names, prices and availability. This view shows demonstration records; the published menu can be inspected separately on the cafe website."), image: "/assets/products/kermez-menu-20261007.webp", points: [pair("صور ووصف وسعر وتصنيف", "Imagery, description, price and category"), pair("تفعيل وأرشفة واستعادة", "Publication, archiving and restoration"), pair("منيو عام مرتبط بإدارة المنتجات", "A public menu linked to product administration")] }
    ],
    scope: pair("منتج مخصص منفذ، تمت مراجعة نسخته المنشورة في 7 أكتوبر 2026. الصور من جولة عامة ببيانات تجريبية والحفظ معطّل فيها. نموذج الحجز يجهّز استفسارًا عبر واتساب؛ يحتاج تأكيد فريق المقهى، ولا يُدخل حجزًا تلقائيًا إلى نظام التشغيل. الأرقام المعروضة في الجولة ليست نتائج النشاط الفعلية.", "An implemented custom product, with the published version reviewed on 7 October 2026. The public demo uses illustrative records and disables saving. The booking form prepares a WhatsApp enquiry requiring cafe confirmation; it does not automatically create a booking in the workspace. Demo figures are not business performance results."),
    question: pair("تحتاج منيو وفريق تشغيل يعملان في مسار واضح؟", "Need a clearer menu and operations workflow?"), next: pair("نحدد طريقة تحديث المنتجات واستقبال الطلبات وأدوار الفريق، ثم نبني الوحدات التي تناسب التشغيل الفعلي.", "Define menu updates, order intake and staff responsibilities, then build the modules your operations need.")
  },
  {
    slug: "alya-catalog-control", code: "ALYA / 05", theme: "alya", stage: "custom", caseSlug: "dahanat-alya-riyadh", previewKind: "public-site",
    name: pair("كتالوج عليا وإدارة المنتجات", "Alya Catalog and Product Administration"), category: pair("كتالوج متجر ولوحة إدارة", "Store catalog and administration"),
    headline: pair("المنتج واضح للعميل.<br>وتحديثه بيد الفريق.", "Clear products for customers.<br>Updates controlled by the team."),
    description: pair("تجربة متجر تجمع هوية عليا وكتالوج المنتجات وصفحاتها المستقلة. وراء الواجهة لوحة خاصة لإدارة الاسم والصورة والوصف والسعر والنشر، مع فصل المنتجات عن خدمات التنفيذ.", "A store experience combining Alya's identity, a searchable catalog and individual product pages. Private administration manages names, imagery, descriptions, prices and publication, while products remain distinct from installation services."),
    audience: pair("إدارة المتجر ومسؤولو المنتجات والمحتوى", "Store managers and product-content staff"),
    problem: pair("يحتاج العميل إلى فهم استخدام المنتج، ويحتاج الفريق إلى تحديث محتواه دون إعادة بناء صفحة الموقع. تربط التجربة العرض العام بإدارة خاصة للمنتجات وتحافظ على وضوح معلومات المتجر.", "Customers need to understand a product's use, while staff need to update it without rebuilding a webpage. The experience links the public catalog with private product management and clear store information."),
    promise: pair("كتالوج حيّ، وصفحات واضحة، وإدارة مستقلة للمحتوى.", "A live catalog, clear pages and managed content."), image: "/assets/projects/alya-catalog-20261007.webp",
    workflow: [pair("يُراجع الفريق بيانات المنتج", "Staff review product details"), pair("يُحدّث المحتوى والنشر", "Content and publication are updated"), pair("يبحث العميل في الكتالوج", "Customers search the catalog"), pair("يراجع المنتج ويتواصل", "They inspect a product and enquire")],
    features: [
      [pair("13 منتجًا وقت المراجعة", "Thirteen products at review"), pair("كتالوج منشور في 7 أكتوبر 2026 يضم منتجات الدهانات والمواد الحرارية، مع تصنيفات وبحث.", "The catalog reviewed on 7 October 2026 contains paint and thermal products, with categories and search.")],
      [pair("صفحة لكل منتج", "Individual product pages"), pair("صورة ومحتوى واستخدامات المنتج، ومسار تواصل قريب من تفاصيله.", "Product imagery, information and uses, with contextual enquiry actions.")],
      [pair("لوحة خاصة للمنتجات", "Private product administration"), pair("إنشاء وتعديل المحتوى والصور والأوصاف والأسعار وحالة النشر من لوحة محمية للفريق.", "Create and edit content, imagery, descriptions, prices and publication state through protected staff administration.")],
      [pair("هوية المتجر والخدمات", "Store identity and services"), pair("هوية بصرية جديدة ومسارات مستقلة لخدمات التنفيذ، بجانب عرض المنتجات.", "A refreshed identity and separate installation-service routes alongside product discovery.")],
      [pair("معلومات الوصول", "Visit information"), pair("بيانات المتجر وساعات العمل ووسائل التواصل والخريطة متسقة مع الملف التجاري.", "Store information, hours, contact routes and Maps aligned with the Business Profile.")],
      [pair("دليل استخدام", "Illustrated handover"), pair("دليل مصور يشرح الموقع وطريقة العمل داخل لوحة إدارة المنتجات.", "An illustrated guide explaining the website and product-management workflow.")]
    ],
    tour: [
      { id: "catalog", label: pair("الكتالوج المنشور", "Published catalog"), title: pair("المنتجات بأسمائها، والاختيار بتصنيفات واضحة.", "Named products with clear browsing routes."), text: pair("صورة حقيقية من الكتالوج العام وقت المراجعة، توضح البحث والتصنيفات وبطاقات المنتجات. يمكن فتح النسخة الحية من دراسة المشروع.", "A genuine capture of the public catalog at review, showing search, categories and product cards. The live version is linked from the case study."), image: "/assets/projects/alya-catalog-20261007.webp", points: [pair("بحث وتصنيفات للمنتجات", "Product search and categories"), pair("صفحات مستقلة للمنتجات", "Dedicated product pages"), pair("13 منتجًا منشورًا وقت المراجعة", "Thirteen published products at review")] },
      { id: "identity", label: pair("تجربة المتجر", "Store experience"), title: pair("هوية واحدة للمنتجات والخدمات والوصول.", "One identity for products, services and visits."), text: pair("الواجهة الحالية تعرّف بالمتجر وتوصل إلى الكتالوج والخدمات والتواصل. الصور هنا من الموقع العام؛ لوحة الإدارة خاصة بالفريق وتُشرح وظائفها ضمن نطاق التنفيذ.", "The current homepage introduces the store and routes visitors to products, services and contact. These captures show the public website; staff administration remains private and its functions are described in the delivery scope."), image: "/assets/projects/alya-home-20261007.webp", points: [pair("هوية الموقع الحالية", "The current website identity"), pair("فصل المنتجات عن خدمات التنفيذ", "Products separate from installation services"), pair("تحديث المحتوى من لوحة خاصة", "Content updates through private administration")] }
    ],
    scope: pair("منتج مخصص منفذ، تمت مراجعة الكتالوج ونسخته العامة في 7 أكتوبر 2026، ومراجعة وظائف إدارة المنتجات من مصدر المشروع ودليل الاستخدام. الصور تعرض الموقع العام، ولوحة الإدارة خاصة بالفريق. النطاق كتالوج واستفسارات وإدارة محتوى؛ لا يتضمن في هذه الجولة دفعًا إلكترونيًا أو تأكيد طلب شراء.", "An implemented custom product. The public catalog was reviewed on 7 October 2026; administration functions were checked against project source and the user guide. Captures show the public site; staff administration is private. This scope covers catalog discovery, enquiries and content management, without online payment or purchase confirmation in the tour."),
    question: pair("تحتاج كتالوجًا يستطيع فريقك تحديثه؟", "Need a catalog your team can update?"), next: pair("نبدأ بتصنيفات المنتجات والبيانات التي يحتاجها العميل ومسؤولية النشر، ثم نربط الواجهة بلوحة إدارة مناسبة.", "Start with product categories, customer information needs and publication responsibilities, then connect the website to suitable administration.")
  }
);
export const productBySlug = new Map(products.map(product => [product.slug, product]));
export const productText = (value, english = false) => value[english ? "en" : "ar"];
