import { site } from "./content.mjs";
import { caseStudies, caseHref, productHref } from "./case-studies.mjs";
import { products, productBySlug, productText } from "./products.mjs";
import { englishProjectStudies } from "./english.mjs";
import { describeCaseScope } from "./case-scope.mjs";

const number = value => String(value).padStart(2, "0");
const stageLabel = (stage, en) => stage === "concept" ? en ? "Interactive product concept" : "تصور منتج تفاعلي" : en ? "Implemented custom product" : "منتج مخصص منفذ";
const statusLabel = (study, en) => study.status === "concept" ? stageLabel("concept", en) : study.status === "private-product" ? stageLabel("custom", en) : study.status === "archived" ? en ? "Saved project version" : "نسخة محفوظة من المشروع" : en ? "Published website" : "موقع منشور";
const image = (src, alt, eager = false) => `<img src="${src}" alt="${alt}" width="1200" height="750" loading="${eager ? "eager" : "lazy"}" decoding="async"${eager ? ' fetchpriority="high"' : ""}>`;
const link = (href, label, icon, ghost = false, external = false) => `<a class="button${ghost ? " button-ghost" : ""}" href="${href}"${external ? ' target="_blank" rel="noopener"' : ""}>${label}${icon(external ? "external" : "arrow", "button-icon")}</a>`;
const crumbs = (items, { english, esc, icon }) => `<nav class="breadcrumbs" aria-label="${english ? "Breadcrumb" : "مسار التنقل"}">${items.map((item, index) => `${index ? icon("chevron") : ""}${item.href ? `<a href="${item.href}">${esc(item.label)}</a>` : `<span aria-current="page">${esc(item.label)}</span>`}`).join("")}</nav>`;

function productCard(product, { english, esc, icon }, compact = false) {
  const t = value => productText(value, english);
  return `<article class="product-card product-theme-${product.theme}${compact ? " product-card-compact" : ""}"><a class="product-card-image" href="${productHref(product.slug, english)}" aria-label="${esc(t(product.name))}"><span class="product-card-code" dir="ltr">${product.code}</span>${image(product.image, esc(english ? `${t(product.name)} demonstration interface` : `واجهة توضيحية لمنتج ${t(product.name)}`))}</a><div class="product-card-copy"><span class="product-status">${stageLabel(product.stage, english)}</span><h3><a href="${productHref(product.slug, english)}">${esc(t(product.name))}</a></h3><p>${esc(t(product.promise))}</p><a class="product-text-link" href="${productHref(product.slug, english)}">${english ? "Explore the product" : "استعرض المنتج"}${icon("arrow")}</a></div></article>`;
}

export function renderProductCollection(options = {}) {
  const { english = false, esc, icon } = options;
  return `<section class="product-collection section-pad" id="digital-products"><div class="container"><div class="product-section-heading"><div><p class="story-kicker" dir="ltr">PRODUCT STUDIO / 03</p><h2>${english ? "Beyond the website.<br>Products that organize work." : "أبعد من موقع.<br>منتجات تنظّم العمل."}</h2></div><div><p>${english ? "Three products, each with a distinct workflow. Explore their purpose, interfaces, and delivery stage through public tours." : "ثلاثة منتجات، لكل منها طريقة عمل مختلفة. اكتشف الفكرة والوظائف والواجهة في جولة مفتوحة لكل منتج."}</p><a class="product-text-link" href="${english ? "/en" : ""}/products/">${english ? "The product collection" : "مجموعة المنتجات"}${icon("arrow")}</a></div></div><div class="product-card-grid">${products.map(product => productCard(product, { english, esc, icon })).join("")}</div></div></section>`;
}

export function renderCaseStudy(study, options) {
  const { english = false, esc, icon } = options;
  const prefix = english ? "/en" : "";
  const name = english ? study.englishName : study.title;
  const product = productBySlug.get(study.productSlug);
  const domain = new URL(study.liveUrl).hostname.replace(/^www\./, "");
  const focus = english ? study.englishFocus : study.focus;
  const productOnly = study.status === "concept" || study.status === "private-product";
  const mainAction = productOnly ? link(productHref(study.productSlug, english), english ? "Explore the product" : "استعرض المنتج", icon)
    : study.liveAvailable ? link(study.liveUrl, english ? "Open the website" : "استكشف الموقع", icon, false, true)
    : link(study.image, english ? "View the saved interface" : "شاهد الواجهة المحفوظة", icon, false, true);
  const tourSteps = productOnly ? product.workflow.map(value => productText(value, english)) : english
    ? ["Choose a relevant route", "Explore the information", "Prepare the enquiry", "Take the next step"] : study.method[4];
  const englishOriginal = englishProjectStudies[study.slug];
  const decisions = english ? englishOriginal?.decisions || [`The experience is organized around one central task: ${study.englishFocus}`, "Organize the experience around the visitor's task, so the first choice leads to relevant information rather than an undifferentiated list.", "Keep the next action close to its context. The interface connects understanding the offer with asking the business a specific question."]
    : study.originalStudy?.decisions || [study.solution, study.method[2], study.method[3]];
  const scopeText = productOnly ? english ? "The module sits within the product workflow described in the public tour. Its role and delivery stage are explained on the separate product page." : "وحدة ضمن مسار المنتج الموضح في الجولة. تُعرض وظيفتها وعلاقتها ببقية العمل، مع توضيح مرحلة المنتج في صفحته المستقلة."
    : english ? "A specific content route in the reviewed experience. It helps visitors identify the relevant information before discussing their own needs with the business."
    : "";
  const scopeNotes = ["إبراز هذا التخصص باسم واضح يساعد الزائر على اختيار مدخل يناسب احتياجه، بدل البحث داخل وصف عام للنشاط.", "وجوده ضمن فئات المحتوى يوضح جزءًا آخر من نطاق العرض، ويُهيئ سؤالًا أكثر تحديدًا عن الحالة أو المساحة المطلوبة.", "يكمل التعريف بالتخصصات التي يعرضها المشروع، ويعطي الزائر سياقًا يستند إليه عند مناقشة طلبه مع الجهة."];
  const related = caseStudies.filter(item => item.sector === study.sector && item.slug !== study.slug && item.status !== "private-product" && item.status !== "concept").slice(0, 2);
  const previous = caseStudies[(study.number + 94) % 96];
  const next = caseStudies[study.number % 96];
  const request = english ? `Hello Eng. Eslam, I read the ${name} case study and would like to discuss a similar project.` : `مرحبًا م. إسلام، قرأت دراسة حالة «${name}» وأرغب في مناقشة مشروع يناسب نشاطي.`;
  return `<article class="project-case" data-case-study="${study.slug}">
<div class="case-hero"><div class="container">${crumbs([{ label: english ? "Home" : "الرئيسية", href: `${prefix}/` }, { label: english ? "Work" : "الأعمال", href: `${prefix}/projects/` }, { label: name }], options)}<div class="case-hero-heading"><div><p class="story-kicker">${english ? "PROJECT CASE STUDY" : "دراسة حالة المشروع"}<span dir="ltr"> / ${number(study.number)}</span></p><h1>${esc(name)}</h1><p class="case-focus">${esc(focus)}</p></div><span class="case-hero-number" aria-hidden="true" dir="ltr">${number(study.number)}<i>↗</i></span></div><div class="case-meta"><span>${icon("layers")}${esc(english ? study.englishSector : study.sector)}</span><span class="case-status">${statusLabel(study, english)}</span><span>${english ? "Design & development: Eslam Elshikh" : "تصميم وتطوير: م. إسلام الشيخ"}</span></div></div></div>
<nav class="case-index" aria-label="${english ? "Case study sections" : "أقسام دراسة الحالة"}"><div class="container">${[["brief", english ? "The challenge" : "التحدي"], ["solution", english ? "The solution" : "الحل"], ["experience", english ? "The experience" : "التجربة"], ["decisions", english ? "Design decisions" : "قرارات التصميم"], ["output", english ? "The output" : "المخرجات"]].map(([id, label]) => `<a href="#${id}">${label}</a>`).join("")}<a class="case-index-all" href="${prefix}/projects/">${english ? "All work" : "كل الأعمال"}${icon("arrow")}</a></div></nav>
<div class="container case-content">
  <section class="case-brief" id="brief"><div><p class="story-kicker">01 / ${english ? "THE DESIGN QUESTION" : "مسألة التصميم"}</p><h2>${english ? "What did this experience need to make clear?" : "ما الذي تحتاج التجربة إلى توضيحه؟"}</h2></div><div class="case-prose"><p>${esc(english ? `The central design task is to make ${study.englishSector.toLowerCase()} understandable through a relevant entry point. ${study.englishFocus} The visitor needs enough context to choose a route and understand the next action.` : study.challenge)}</p><dl class="case-brief-facts"><div><dt>${english ? "The audience" : "المستخدم"}</dt><dd>${esc(english ? productOnly ? productText(product.audience, true) : `Visitors exploring ${study.englishSector.toLowerCase()}` : productOnly ? productText(product.audience) : study.method[0])}</dd></div><div><dt>${english ? "The core task" : "المهمة الأساسية"}</dt><dd>${esc(english ? study.englishFocus : productOnly ? productText(product.promise) : study.method[1])}</dd></div></dl></div></section>
  <section class="case-solution" id="solution"><div class="case-section-title"><p class="story-kicker">02 / ${english ? "THE SOLUTION" : "الحل"}</p><h2>${english ? "A structure shaped by the task." : "بنية تخدم ما جاء المستخدم لأجله."}</h2><p>${esc(english ? study.englishNarrative : study.solution)}</p></div><figure class="case-interface"><a href="${study.image}" target="_blank" rel="noopener" aria-label="${english ? "Open the full interface image" : "عرض صورة الواجهة كاملة"}"><span class="case-browser"><span class="case-browser-dots" aria-hidden="true">● ● ●</span><span dir="ltr">${esc(productOnly ? `${product.code} / PRODUCT TOUR` : domain)}</span>${icon("external")}</span>${image(study.image, esc(english ? `Reviewed interface of ${name}` : `الواجهة المعروضة لمشروع ${name}`), true)}</a><figcaption><span>${productOnly ? english ? "Actual interface · labelled demonstration data" : "واجهة المنتج · بيانات تجريبية موضحة" : study.liveAvailable ? english ? "Project interface · open the image to inspect it" : "واجهة المشروع · افتح الصورة لمراجعتها كاملة" : english ? "Saved preview of the original project interface" : "معاينة محفوظة من واجهة المشروع الأصلية"}</span>${mainAction}</figcaption></figure><div class="case-scope-grid">${study.topics.map((topic, index) => `<div class="case-scope-card"><span dir="ltr">${number(index + 1)} / SCOPE</span><h3${english ? ' lang="ar" dir="rtl"' : ""}>${esc(topic)}</h3><p>${esc(productOnly || english ? scopeText : scopeNotes[index])}</p></div>`).join("")}</div></section>
  <section class="case-experience" id="experience"><p class="story-kicker">03 / ${english ? "THE USER JOURNEY" : "رحلة المستخدم"}</p><h2>${english ? "From the first question to the next action." : "من أول سؤال، إلى الخطوة التالية."}</h2><ol class="case-journey">${tourSteps.map((step, index) => `<li><span dir="ltr">${number(index + 1)}</span><strong>${esc(step)}</strong></li>`).join("")}</ol></section>
  <section class="case-decisions" id="decisions"><div><p class="story-kicker">04 / ${english ? "DESIGN REASONING" : "منطق التصميم"}</p><h2>${english ? "Every choice has a purpose." : "كل اختيار في الواجهة له سبب."}</h2><p>${english ? "The layout connects content, visitor intent, and the business workflow." : "ترتيب المحتوى ووسائل الانتقال والتواصل مرتبط بطبيعة النشاط، وما يحتاج المستخدم إلى فهمه قبل اتخاذ قراره."}</p></div><ol>${decisions.slice(0, 3).map((item, index) => `<li><span dir="ltr">${number(index + 1)}</span><p>${esc(item)}</p></li>`).join("")}</ol></section>
  <section class="case-output" id="output"><div><p class="story-kicker">05 / ${english ? "REVIEWABLE OUTPUT" : "المخرجات"}</p><h2>${english ? "The result, in the experience itself." : "النتيجة، كما تظهر في التجربة."}</h2><p>${esc(english ? `The reviewed experience brings together a defined interface, content routes, and contextual next-step actions. ${productOnly ? "The public product tour documents the modules and delivery stage." : "The interface preview and project link make the structure available to inspect."}` : study.outcome)}</p></div><div class="case-output-proof"><span>${english ? "READY TO REVIEW" : "يمكنك مراجعته"}</span><ul><li>${icon("check")}${english ? "The published interface or public product tour" : "الواجهة المنشورة أو الجولة العامة للمنتج"}</li><li>${icon("check")}${english ? "The content structure and navigation" : "بنية المحتوى وطريقة الانتقال بين أجزائه"}</li><li>${icon("check")}${english ? "The context and placement of the next action" : "علاقة الخدمة أو الوظيفة بالخطوة التالية"}</li></ul>${mainAction}</div></section>
  ${product ? `<aside class="case-product-bridge product-theme-${product.theme}"><div><span class="story-kicker">${english ? "THE INDEPENDENT PRODUCT" : "المنتج المستقل"}</span><h2>${esc(productText(product.name, english))}</h2><p>${esc(productText(product.promise, english))}</p>${link(productHref(product.slug, english), english ? "Take the product tour" : "ادخل جولة المنتج", icon)}</div><a href="${productHref(product.slug, english)}" aria-label="${esc(productText(product.name, english))}">${image(product.image, esc(productText(product.name, english)))}</a></aside>` : ""}
  <details class="case-evidence-note"><summary>${english ? "About this case study" : "عن هذه الدراسة"}${icon("chevron")}</summary><p>${english ? "The study documents the reviewed interface and explains its design approach. It does not claim traffic, conversion, or return-on-investment figures. Product tours use labelled demonstration data, and product concepts are identified as such." : "توثق الدراسة الواجهة المعروضة وتشرح منطق التصميم. لا تتضمن هذه الدراسة أرقام زيارات أو تحويلات أو عائد استثمار. تستخدم جولات المنتجات بيانات تجريبية موضحة، ويُشار إلى تصورات المنتجات بصفتها تصورات."}</p></details>
  <section class="case-next"><div><p class="story-kicker">${english ? "YOUR PROJECT" : "مشروعك القادم"}</p><h2>${english ? "A similar method.<br>An experience of your own." : "نفس عمق التفكير.<br>وتجربة تخص نشاطك."}</h2><p>${english ? "Tell me about your audience, workflow, and the experience you want to build. We can define the right scope together." : "احكي لي عن جمهورك وطريقة عملك والتجربة التي تريد بناءها. نحدد النطاق المناسب، ثم نصمم حلًا يشرح نشاطك ويخدم مستخدميك."}</p>${link(`${site.whatsapp}?text=${encodeURIComponent(request)}`, english ? "Discuss your project" : "ناقش مشروعك", icon, false, true)}</div><div class="case-related"><span>${english ? "MORE PERSPECTIVES" : "حكايات أخرى"}</span>${related.map(item => `<a href="${caseHref(item, english)}">${image(item.image, esc(english ? item.englishName : item.title))}<span><small>${esc(english ? item.englishSector : item.sector)}</small><strong>${esc(english ? item.englishName : item.title)}</strong></span>${icon("arrow")}</a>`).join("")}</div></section>
  <nav class="case-pagination" aria-label="${english ? "Other case studies" : "دراسات أخرى"}"><a href="${caseHref(previous, english)}"><small>${english ? "Previous case study" : "الدراسة السابقة"}</small><strong>${esc(english ? previous.englishName : previous.title)}</strong></a><a href="${caseHref(next, english)}"><small>${english ? "Next case study" : "الدراسة التالية"}</small><strong>${esc(english ? next.englishName : next.title)}</strong>${icon("arrow")}</a></nav>
</div></article>`;
}

export function renderProductsIndex(options) {
  const { english = false, esc, icon } = options;
  const prefix = english ? "/en" : "";
  return `<div class="product-index-page"><div class="product-index-hero"><div class="container">${crumbs([{ label: english ? "Home" : "الرئيسية", href: `${prefix}/` }, { label: english ? "Products" : "المنتجات" }], options)}<p class="story-kicker" dir="ltr">ESLAM ELSHIKH / PRODUCT STUDIO</p><h1>${english ? "Interfaces you see.<br><em>Workflows you understand.</em>" : "واجهات تراها.<br><em>وطريقة عمل تفهمها.</em>"}</h1><p>${english ? "A collection of custom products and interactive concepts. Each product has its own audience, purpose, and public interface tour." : "منتجات مخصصة وتصورات تفاعلية، لكل منها جمهور ومهمة وطريقة عمل. هنا يمكنك استعراض الواجهة وفهم دورها داخل العمل."}</p><a class="product-text-link" href="#digital-products">${english ? "Meet the three products" : "تعرّف على المنتجات الثلاثة"}${icon("arrow")}</a></div></div>${renderProductCollection(options)}<section class="section-pad product-comparison"><div class="container"><div class="product-section-heading"><div><p class="story-kicker">${english ? "THE RIGHT FIT" : "الاستخدام المناسب"}</p><h2>${english ? "Each product answers<br>a different question." : "كل منتج يجيب<br>عن سؤال مختلف."}</h2></div><p>${english ? "Choose by workflow and audience. Delivery stage is shown alongside each product." : "اختَر بحسب المهمة والفريق الذي سيستخدم المنتج. مرحلة التنفيذ موضحة لكل تجربة."}</p></div><div class="product-comparison-table"><table><caption class="visually-hidden">${english ? "Product purpose and stage" : "مقارنة هدف المنتجات ومرحلتها"}</caption><thead><tr><th scope="col">${english ? "Product" : "المنتج"}</th><th scope="col">${english ? "Who it serves" : "لمن؟"}</th><th scope="col">${english ? "Core purpose" : "المهمة"}</th><th scope="col">${english ? "Stage" : "المرحلة"}</th></tr></thead><tbody>${products.map(product => `<tr><th scope="row"><a href="${productHref(product.slug, english)}">${esc(productText(product.name, english))}</a></th><td>${esc(productText(product.audience, english))}</td><td>${esc(productText(product.category, english))}</td><td>${stageLabel(product.stage, english)}</td></tr>`).join("")}</tbody></table></div></div></section><section class="product-final-cta"><div class="container"><span class="story-kicker">${english ? "BUILD AROUND YOUR TEAM" : "منتج يناسب فريقك"}</span><h2>${english ? "Start with the workflow.<br>Build the right product." : "نبدأ من طريقة العمل.<br>ونبني المنتج المناسب."}</h2><p>${english ? "Define the users, daily tasks, and data sources first. The interface and product scope follow that understanding." : "نفهم المستخدمين والمهام اليومية ومصادر البيانات أولًا. بعدها نحدد النطاق ونبني واجهة تساعد الفريق في عمله."}</p>${link(`${prefix}/contact/`, english ? "Discuss a custom product" : "ناقش منتجًا مخصصًا", icon)}</div></section></div>`;
}

export function renderProductPage(product, options) {
  const { english = false, esc, icon } = options;
  const prefix = english ? "/en" : "";
  const t = value => productText(value, english);
  const request = english ? `Hello Eng. Eslam, I explored ${t(product.name)} and would like to discuss a product for my team's workflow.` : `مرحبًا م. إسلام، استعرضت منتج «${t(product.name)}» وأرغب في عرض توضيحي ومناقشة منتج يناسب طريقة عمل فريقي.`;
  return `<article class="product-page product-theme-${product.theme}" data-product="${product.slug}"><div class="product-hero"><div class="container">${crumbs([{ label: english ? "Home" : "الرئيسية", href: `${prefix}/` }, { label: english ? "Products" : "المنتجات", href: `${prefix}/products/` }, { label: t(product.name) }], options)}<div class="product-hero-topline"><p class="story-kicker" dir="ltr">${product.code} / PRODUCT STUDIO</p><span class="product-status">${stageLabel(product.stage, english)}</span></div><div class="product-hero-copy"><p class="product-name">${esc(t(product.name))}</p><h1>${t(product.headline)}</h1><p>${esc(t(product.description))}</p><div class="product-hero-actions">${link("#product-tour", english ? "Explore the interface tour" : "ادخل جولة الواجهة", icon)}${link(`${site.whatsapp}?text=${encodeURIComponent(request)}`, english ? "Request a walkthrough" : "اطلب عرضًا توضيحيًا", icon, true, true)}</div><span class="product-hero-audience">${icon("user")}${esc(t(product.audience))}</span></div><figure class="product-hero-screen"><span class="product-screen-bar"><span dir="ltr">${product.code} / WORKSPACE</span><span>${english ? "Demonstration interface" : "واجهة توضيحية"}</span></span>${image(product.image, esc(`${t(product.name)} — ${english ? "demonstration interface" : "واجهة ببيانات تجريبية"}`), true)}<figcaption>${english ? "Actual product interface rendered with labelled demonstration data." : "واجهة المنتج الفعلية مع بيانات تجريبية موضحة داخل الصور."}</figcaption></figure></div></div>
<section class="section-pad product-purpose"><div class="container"><div class="product-purpose-grid"><div><p class="story-kicker">01 / ${english ? "WHY THIS PRODUCT" : "لماذا هذا المنتج؟"}</p><h2>${esc(t(product.promise))}</h2></div><p>${esc(t(product.problem))}</p></div><ol class="product-workflow">${product.workflow.map((step, index) => `<li><span dir="ltr">${number(index + 1)}</span><strong>${esc(t(step))}</strong></li>`).join("")}</ol></div></section>
<section class="section-pad product-tour-section" id="product-tour"><div class="container"><div class="product-section-heading"><div><p class="story-kicker">02 / ${english ? "INSIDE THE PRODUCT" : "داخل المنتج"}</p><h2>${english ? "See how the work connects." : "شاهد كيف تترابط التفاصيل."}</h2></div><p>${english ? "Choose a view to inspect the interface and its role in the workflow. All images use demonstration data." : "اختَر الشاشة، وشاهد الواجهة ودورها في سير العمل. الصور كلها تستخدم بيانات عرض توضيحية."}</p></div><div class="product-tour" data-product-tour><div class="product-tour-tabs" aria-label="${english ? "Product tour views" : "شاشات جولة المنتج"}">${product.tour.map((view, index) => `<button type="button" data-product-tab="${view.id}" id="product-tab-${view.id}" aria-controls="product-panel-${view.id}"><span dir="ltr">${number(index + 1)}</span>${esc(t(view.label))}${icon("arrow")}</button>`).join("")}</div><div class="product-tour-panels">${product.tour.map(view => `<section class="product-tour-panel" id="product-panel-${view.id}" data-product-panel="${view.id}" aria-labelledby="product-tab-${view.id}"><div class="product-tour-copy"><span class="story-kicker">${esc(t(view.label))}</span><h3>${esc(t(view.title))}</h3><p>${esc(t(view.text))}</p><ul>${view.points.map(point => `<li>${icon("check")}${esc(t(point))}</li>`).join("")}</ul></div><figure><a href="${view.image}" target="_blank" rel="noopener" aria-label="${english ? "Open full view" : "افتح الصورة كاملة"} — ${esc(t(view.label))}">${image(view.image, esc(`${t(product.name)} — ${t(view.label)} — ${english ? "demonstration data" : "بيانات تجريبية"}`))}<span>${icon("search")}${english ? "Inspect the full interface" : "راجع الواجهة كاملة"}</span></a><figcaption>${english ? "Actual interface · demonstration records only" : "واجهة فعلية · سجلات توضيحية فقط"}</figcaption></figure></section>`).join("")}</div></div></div></section>
<section class="section-pad product-features"><div class="container"><div class="product-section-heading"><div><p class="story-kicker">03 / ${english ? "PRODUCT CAPABILITIES" : "وحدات المنتج"}</p><h2>${english ? "Details that serve the workflow." : "تفاصيل تخدم العمل اليومي."}</h2></div><p>${esc(t(product.category))}</p></div><div class="product-feature-grid">${product.features.map(([title, text], index) => `<article><span dir="ltr">${number(index + 1)}</span><h3>${esc(t(title))}</h3><p>${esc(t(text))}</p></article>`).join("")}</div></div></section>
<section class="section-pad product-scope"><div class="container"><div><span class="product-status">${stageLabel(product.stage, english)}</span><h2>${english ? "The product's delivery stage and scope." : "مرحلة المنتج ونطاقه."}</h2><p>${esc(t(product.scope))}</p></div><a class="product-text-link" href="${prefix}/projects/${product.caseSlug}/">${english ? "Read the project case study" : "اقرأ دراسة حالة المشروع"}${icon("arrow")}</a></div></section>
<section class="product-final-cta"><div class="container"><p class="story-kicker">${english ? "LET'S DESIGN YOUR WORKFLOW" : "نصمم طريقة عملك"}</p><h2>${esc(t(product.question))}</h2><p>${esc(t(product.next))}</p><div class="product-hero-actions">${link(`${site.whatsapp}?text=${encodeURIComponent(request)}`, english ? "Request a walkthrough" : "اطلب عرضًا توضيحيًا", icon, false, true)}${link(`${prefix}/products/`, english ? "All products" : "كل المنتجات", icon, true)}</div></div></section></article>`;
}
