const pair=(ar,en)=>({ar,en});
const presentations={
 'crm-systems':{code:'YOUR BUSINESS / YOUR SYSTEM',question:pair('كيف سيعمل CRM داخل نشاطي؟','How would CRM work in my business?'),value:pair('اختبر مسارًا تفاعليًا، ثم اطلب تجربة فعلية بهوية منشأتك وأدوار فريقك ومهامه.','Try an interactive workflow, then request a working custom trial with your identity, team roles and tasks.'),points:[pair('تجربة مخصصة','Custom trial'),pair('عملاء ومتابعات','Customers & follow-up'),pair('أدوار وصلاحيات','Roles & access')]},
 'web-development':{code:'DESIGN / BUILD / LAUNCH',question:pair('أحتاج موقعًا يشرح عملي ويخدم عميلي','I need a website that serves my customers'),value:pair('واجهة واضحة، وتجربة متجاوبة، وبنية تجعل خدماتك وخطوة التواصل مفهومة.','Clear interfaces, responsive journeys and a structure that explains your services and next action.'),points:[pair('تصميم وتجربة','Design & experience'),pair('تطوير وربط','Build & connect'),pair('اختبار وإطلاق','Test & launch')]},
 'cybersecurity':{code:'ASSESS / PRIORITIZE / VERIFY',question:pair('أريد معرفة المخاطر قبل أن تؤثر على عملي','I need to understand my security risks'),value:pair('تقييم ضمن نطاق مصرح، وأولويات معالجة مرتبطة بأثرها على الموقع والتشغيل.','An authorized assessment with remediation priorities connected to their operational impact.'),points:[pair('مواقع وواجهات API','Websites & APIs'),pair('صلاحيات وحسابات','Access & accounts'),pair('معالجة وتحقق','Fix & verify')]},
 'cloud-solutions':{code:'ARCHITECTURE / OPERATIONS',question:pair('أحتاج بنية تستوعب مشروعي وتبقى قابلة للإدارة','I need infrastructure I can operate'),value:pair('بنية استضافة وصلاحيات ونسخ احتياطي تُصمم حسب الاستخدام والميزانية.','Hosting, access and backup architecture matched to usage, operational needs and budget.'),points:[pair('معمارية واستضافة','Architecture & hosting'),pair('بيئات وصلاحيات','Environments & access'),pair('مراقبة وتكلفة','Monitoring & cost')]},
 'ai-agents':{code:'KNOWLEDGE / ACTION / REVIEW',question:pair('أريد اختصار مهمة متكررة في فريقي','I want to simplify a recurring team task'),value:pair('مساعد أو وكيل يؤدي مهمة محددة، بمصادر واضحة وحدود وتدخل بشري عند الحاجة.','An assistant or agent for a defined task, with clear sources, boundaries and human review.'),points:[pair('مساعدات معرفة','Knowledge assistants'),pair('أتمتة مهام','Task automation'),pair('تقييم وتكامل','Evaluation & integration')]},
 'google-support':{code:'DIAGNOSE / DOCUMENT / FOLLOW',question:pair('أحتاج فهم مشكلة في منتج من Google','I need clarity on a Google product issue'),value:pair('قراءة الإشعار والأدلة، وتحديد المسار المناسب، وترتيب متابعة الحالة.','Review the notice and evidence, identify the appropriate route and organize follow-up.'),points:[pair('تشخيص الحالة','Case diagnosis'),pair('ترتيب الأدلة','Evidence preparation'),pair('دعم ومتابعة','Support & follow-up')]},
 'google-business-profile':{code:'PROFILE / ELIGIBILITY / VISIBILITY',question:pair('ملفي التجاري يحتاج إعدادًا أو معالجة','My Business Profile needs attention'),value:pair('مراجعة الإعداد والتحقق والتعليق والملكية، وتحسين البيانات وفق واقع النشاط.','Review setup, verification, suspension and ownership while aligning information with the real business.'),points:[pair('إعداد وتحقق','Setup & verification'),pair('تعليق وملكية','Suspension & ownership'),pair('بيانات وظهور','Information & visibility')]},
 'knowledge-bases':{code:'CONTENT / STRUCTURE / SEARCH',question:pair('المعلومة موجودة؛ أريد الوصول إليها بسهولة','I need useful information to be easier to find'),value:pair('تنظيم المعرفة والمصادر والبحث، حتى يصل الفريق إلى معلومة لها سياق ومرجع.','Organize knowledge, sources and search so staff can find information with context and provenance.'),points:[pair('تنظيم المحتوى','Content structure'),pair('بحث نصي ودلالي','Text & semantic search'),pair('مصادر وصلاحيات','Sources & access')]},
 'seo':{code:'CRAWL / INTENT / EXPERIENCE',question:pair('أريد أن تُفهم خدماتي في البحث','I want search to understand my services'),value:pair('فحص تقني ومحتوى وروابط داخلية تشرح خدماتك وتخدم نية الباحث.','Technical review, useful content and internal links that explain services and satisfy search intent.'),points:[pair('فحص وفهرسة','Crawling & indexing'),pair('محتوى وبنية','Content & architecture'),pair('قياس وتحسين','Measurement & improvement')]},
 'digital-advertising':{code:'AUDIENCE / LANDING / MEASUREMENT',question:pair('أحتاج حملة لها هدف وقياس واضح','I need a campaign with a clear objective'),value:pair('حملات وصفحات هبوط وتتبع للتحويلات، مع مراجعة جودة الطلبات والميزانية.','Campaigns, landing pages and conversion measurement, with review of lead quality and budget.'),points:[pair('حملات بحث','Search campaigns'),pair('صفحات هبوط','Landing pages'),pair('تحويلات وميزانية','Conversions & budget')]}
};
const ordering=['crm-systems','web-development','ai-agents','cybersecurity','cloud-solutions','google-business-profile','google-support','seo','knowledge-bases','digital-advertising'];
export const orderedServices=services=>[...services].sort((a,b)=>ordering.indexOf(a.slug)-ordering.indexOf(b.slug));
export function renderServiceCard(service,{english=false,esc,icon}){
 const v=presentations[service.slug];const t=x=>x[english?'en':'ar'];const url=`${english?'/en':''}/services/${service.slug}/`;const featured=service.slug==='crm-systems';
 return `<article class="service-card reveal" data-service-group="${esc(service.group)}" data-service-kind="${service.slug}"><div class="service-card-main"><div class="service-card-top"><span class="service-number" dir="ltr">${service.number} / ${v.code}</span><span class="service-icon">${icon(service.icon)}</span></div><p class="service-group">${featured?(english?'A working trial for your business':'تجربة فعلية مخصصة لنشاطك'):esc(service.group)}</p><h3><a href="${url}">${esc(service.title)}</a></h3><p class="service-entry-question">${esc(t(v.question))}</p><p class="service-value">${esc(t(v.value))}</p><ul class="service-scope-tags" aria-label="${english?'Key workstreams':'أبرز المسارات'}">${v.points.map(point=>`<li>${esc(t(point))}</li>`).join('')}</ul><a class="text-link" href="${url}${featured?'#crm-personal-trial':''}" aria-label="${english?'View '+esc(service.title)+' service details':'تفاصيل خدمة '+esc(service.title)}">${featured?(english?'Try the workflow & shape your trial':'جرّب المسار وحدّد تجربتك'):(english?'Explore the scope':'استكشف نطاق الخدمة')}${icon('arrow')}</a></div>${featured?`<div class="service-card-visual" aria-hidden="true"><div class="service-visual-head"><span>YOUR BRAND</span><span>CRM / WORKSPACE</span></div><div class="service-visual-brand">${icon('layers')}<span>${english?'Your business. Your workflow.':'منشأتك. وطريقة عملك.'}</span></div><div class="service-visual-lanes"><span>${english?'Customer':'عميل'}</span><i></i><span>${english?'Request':'طلب'}</span><i></i><span>${english?'Next step':'خطوة قادمة'}</span></div><div class="service-visual-roles">${icon('user')}<span>${english?'Record. Assign. Follow up.':'سجّل طلبًا. عيّن المسؤول. جرّب المتابعة.'}</span>${icon('check')}</div></div>`:''}</article>`;
}
export function renderServiceIntro({english=false,icon}){
 return `<div class="services-studio-heading"><div><p class="service-eyebrow" dir="ltr">ESLAM ELSHIKH / CONNECTED CAPABILITIES</p><h2>${english?'Start with your goal.<br><em>Find the right service.</em>':'ابدأ بهدفك.<br><em>واختر الخدمة المناسبة.</em>'}</h2></div><div><p>${english?'Build a presence, organize work, protect a system or improve discovery. Each service explains its starting point, workstreams and next action. Combine them where your project needs it.':'ابنِ حضورك، أو نظّم عملك، أو احمِ نظامك، أو حسّن وصول العملاء إليك. كل خدمة توضح نقطة البداية ومسارات العمل والخطوة التالية، ويمكن دمجها بحسب احتياج مشروعك.'}</p><div class="service-journey"><span>${icon('search')}${english?'Understand':'نفهم'}</span><i></i><span>${icon('layers')}${english?'Build':'نبني'}</span><i></i><span>${icon('chart')}${english?'Improve':'نحسّن'}</span></div></div></div>`;
}
